/*
 * generated by Xtext
 */
package org.ckr.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractTabletUIDSLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.ckr.tabletUIDSL.TabletUIDSLPackage.eINSTANCE);
		return result;
	}
}
