/*
 * generated by Xtext
 */
package org.ckr.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TabletUIDSLUiModule extends org.ckr.ui.AbstractTabletUIDSLUiModule {
	public TabletUIDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
