/*
 * generated by Xtext
 */
package org.ckr;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TabletUIDSLRuntimeModule extends org.ckr.AbstractTabletUIDSLRuntimeModule {

	
	
}
