/*
 * generated by Xtext
 */
package org.ckr.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.ckr.services.TabletUIDSLGrammarAccess;

public class TabletUIDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TabletUIDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.ckr.parser.antlr.internal.InternalTabletUIDSLParser createParser(XtextTokenStream stream) {
		return new org.ckr.parser.antlr.internal.InternalTabletUIDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "TabletUI";
	}
	
	public TabletUIDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TabletUIDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
