/*
 * generated by Xtext
 */
package org.ckr.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class TabletUIDSLGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class TabletUIElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TabletUI");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSettingsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSettingsSettingsParserRuleCall_0_0 = (RuleCall)cSettingsAssignment_0.eContents().get(0);
		private final Assignment cElementsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cElementsAbstractElementParserRuleCall_1_0 = (RuleCall)cElementsAssignment_1.eContents().get(0);
		
		//TabletUI:
		//	settings=Settings elements+=AbstractElement*;
		@Override public ParserRule getRule() { return rule; }

		//settings=Settings elements+=AbstractElement*
		public Group getGroup() { return cGroup; }

		//settings=Settings
		public Assignment getSettingsAssignment_0() { return cSettingsAssignment_0; }

		//Settings
		public RuleCall getSettingsSettingsParserRuleCall_0_0() { return cSettingsSettingsParserRuleCall_0_0; }

		//elements+=AbstractElement*
		public Assignment getElementsAssignment_1() { return cElementsAssignment_1; }

		//AbstractElement
		public RuleCall getElementsAbstractElementParserRuleCall_1_0() { return cElementsAbstractElementParserRuleCall_1_0; }
	}

	public class SettingsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Settings");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSettingsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTitleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTitleAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTitleSTRINGTerminalRuleCall_2_0 = (RuleCall)cTitleAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFhemweb_urlKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFhemweb_urlAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cFhemweb_urlSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cFhemweb_urlAssignment_3_1.eContents().get(0);
		private final Keyword cWidthKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cWidthAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cWidthINTTerminalRuleCall_5_0 = (RuleCall)cWidthAssignment_5.eContents().get(0);
		private final Keyword cHeightKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cHeightAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cHeightINTTerminalRuleCall_7_0 = (RuleCall)cHeightAssignment_7.eContents().get(0);
		private final Keyword cColumnsKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cColumnsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cColumnsINTTerminalRuleCall_9_0 = (RuleCall)cColumnsAssignment_9.eContents().get(0);
		private final Keyword cRowsKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cRowsAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cRowsINTTerminalRuleCall_11_0 = (RuleCall)cRowsAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cDebugKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cDebugAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cDebugBOOLParserRuleCall_12_1_0 = (RuleCall)cDebugAssignment_12_1.eContents().get(0);
		private final Keyword cDragDropKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cDragdropAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cDragdropBOOLParserRuleCall_14_0 = (RuleCall)cDragdropAssignment_14.eContents().get(0);
		private final Keyword cGridster_marginKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cMarginAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cMarginINTTerminalRuleCall_16_0 = (RuleCall)cMarginAssignment_16.eContents().get(0);
		private final Assignment cSettingsAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cSettingsSettingsElementParserRuleCall_17_0 = (RuleCall)cSettingsAssignment_17.eContents().get(0);
		
		//Settings:
		//	"settings" "title" title=STRING ("fhemweb_url" fhemweb_url=STRING)? "width" width=INT "height" height=INT "columns"
		//	columns=INT "rows" rows=INT ("debug" debug=BOOL)? "drag&drop" dragdrop=BOOL "gridster_margin" margin=INT
		//	settings+=SettingsElement*;
		@Override public ParserRule getRule() { return rule; }

		//"settings" "title" title=STRING ("fhemweb_url" fhemweb_url=STRING)? "width" width=INT "height" height=INT "columns"
		//columns=INT "rows" rows=INT ("debug" debug=BOOL)? "drag&drop" dragdrop=BOOL "gridster_margin" margin=INT
		//settings+=SettingsElement*
		public Group getGroup() { return cGroup; }

		//"settings"
		public Keyword getSettingsKeyword_0() { return cSettingsKeyword_0; }

		//"title"
		public Keyword getTitleKeyword_1() { return cTitleKeyword_1; }

		//title=STRING
		public Assignment getTitleAssignment_2() { return cTitleAssignment_2; }

		//STRING
		public RuleCall getTitleSTRINGTerminalRuleCall_2_0() { return cTitleSTRINGTerminalRuleCall_2_0; }

		//("fhemweb_url" fhemweb_url=STRING)?
		public Group getGroup_3() { return cGroup_3; }

		//"fhemweb_url"
		public Keyword getFhemweb_urlKeyword_3_0() { return cFhemweb_urlKeyword_3_0; }

		//fhemweb_url=STRING
		public Assignment getFhemweb_urlAssignment_3_1() { return cFhemweb_urlAssignment_3_1; }

		//STRING
		public RuleCall getFhemweb_urlSTRINGTerminalRuleCall_3_1_0() { return cFhemweb_urlSTRINGTerminalRuleCall_3_1_0; }

		//"width"
		public Keyword getWidthKeyword_4() { return cWidthKeyword_4; }

		//width=INT
		public Assignment getWidthAssignment_5() { return cWidthAssignment_5; }

		//INT
		public RuleCall getWidthINTTerminalRuleCall_5_0() { return cWidthINTTerminalRuleCall_5_0; }

		//"height"
		public Keyword getHeightKeyword_6() { return cHeightKeyword_6; }

		//height=INT
		public Assignment getHeightAssignment_7() { return cHeightAssignment_7; }

		//INT
		public RuleCall getHeightINTTerminalRuleCall_7_0() { return cHeightINTTerminalRuleCall_7_0; }

		//"columns"
		public Keyword getColumnsKeyword_8() { return cColumnsKeyword_8; }

		//columns=INT
		public Assignment getColumnsAssignment_9() { return cColumnsAssignment_9; }

		//INT
		public RuleCall getColumnsINTTerminalRuleCall_9_0() { return cColumnsINTTerminalRuleCall_9_0; }

		//"rows"
		public Keyword getRowsKeyword_10() { return cRowsKeyword_10; }

		//rows=INT
		public Assignment getRowsAssignment_11() { return cRowsAssignment_11; }

		//INT
		public RuleCall getRowsINTTerminalRuleCall_11_0() { return cRowsINTTerminalRuleCall_11_0; }

		//("debug" debug=BOOL)?
		public Group getGroup_12() { return cGroup_12; }

		//"debug"
		public Keyword getDebugKeyword_12_0() { return cDebugKeyword_12_0; }

		//debug=BOOL
		public Assignment getDebugAssignment_12_1() { return cDebugAssignment_12_1; }

		//BOOL
		public RuleCall getDebugBOOLParserRuleCall_12_1_0() { return cDebugBOOLParserRuleCall_12_1_0; }

		//"drag&drop"
		public Keyword getDragDropKeyword_13() { return cDragDropKeyword_13; }

		//dragdrop=BOOL
		public Assignment getDragdropAssignment_14() { return cDragdropAssignment_14; }

		//BOOL
		public RuleCall getDragdropBOOLParserRuleCall_14_0() { return cDragdropBOOLParserRuleCall_14_0; }

		//"gridster_margin"
		public Keyword getGridster_marginKeyword_15() { return cGridster_marginKeyword_15; }

		//margin=INT
		public Assignment getMarginAssignment_16() { return cMarginAssignment_16; }

		//INT
		public RuleCall getMarginINTTerminalRuleCall_16_0() { return cMarginINTTerminalRuleCall_16_0; }

		//settings+=SettingsElement*
		public Assignment getSettingsAssignment_17() { return cSettingsAssignment_17; }

		//SettingsElement
		public RuleCall getSettingsSettingsElementParserRuleCall_17_0() { return cSettingsSettingsElementParserRuleCall_17_0; }
	}

	public class SettingsElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SettingsElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCSSParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cColorParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//SettingsElement:
		//	CSS | Color;
		@Override public ParserRule getRule() { return rule; }

		//CSS | Color
		public Alternatives getAlternatives() { return cAlternatives; }

		//CSS
		public RuleCall getCSSParserRuleCall_0() { return cCSSParserRuleCall_0; }

		//Color
		public RuleCall getColorParserRuleCall_1() { return cColorParserRuleCall_1; }
	}

	public class CSSElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CSS");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCssKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPathAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPathSTRINGTerminalRuleCall_1_0 = (RuleCall)cPathAssignment_1.eContents().get(0);
		
		//CSS:
		//	"css" path=STRING;
		@Override public ParserRule getRule() { return rule; }

		//"css" path=STRING
		public Group getGroup() { return cGroup; }

		//"css"
		public Keyword getCssKeyword_0() { return cCssKeyword_0; }

		//path=STRING
		public Assignment getPathAssignment_1() { return cPathAssignment_1; }

		//STRING
		public RuleCall getPathSTRINGTerminalRuleCall_1_0() { return cPathSTRINGTerminalRuleCall_1_0; }
	}

	public class AbstractElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AbstractElement");
		private final RuleCall cPageParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//AbstractElement:
		//	Page;
		@Override public ParserRule getRule() { return rule; }

		//Page
		public RuleCall getPageParserRuleCall() { return cPageParserRuleCall; }
	}

	public class BOOLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BOOL");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//BOOL:
		//	"true" | "false";
		@Override public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}

	public class PageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Page");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cElementsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cElementsGridsterParserRuleCall_2_0 = (RuleCall)cElementsAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Page:
		//	name=ID "{" elements+=Gridster* "}";
		@Override public ParserRule getRule() { return rule; }

		//name=ID "{" elements+=Gridster* "}"
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//elements+=Gridster*
		public Assignment getElementsAssignment_2() { return cElementsAssignment_2; }

		//Gridster
		public RuleCall getElementsGridsterParserRuleCall_2_0() { return cElementsGridsterParserRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}

	public class GridsterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Gridster");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cHeaderKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cHeaderAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cHeaderSTRINGTerminalRuleCall_1_1_0 = (RuleCall)cHeaderAssignment_1_1.eContents().get(0);
		private final Keyword cRowKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRowAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRowINTTerminalRuleCall_3_0 = (RuleCall)cRowAssignment_3.eContents().get(0);
		private final Keyword cColumnKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cColumnAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cColumnINTTerminalRuleCall_5_0 = (RuleCall)cColumnAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cColspanKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cColspanAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cColspanINTTerminalRuleCall_6_1_0 = (RuleCall)cColspanAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cRowspanKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cRowspanAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cRowspanINTTerminalRuleCall_7_1_0 = (RuleCall)cRowspanAssignment_7_1.eContents().get(0);
		private final Assignment cColorsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cColorsColorParserRuleCall_8_0 = (RuleCall)cColorsAssignment_8.eContents().get(0);
		private final Assignment cWidgetsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cWidgetsWidgetParserRuleCall_9_0 = (RuleCall)cWidgetsAssignment_9.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Gridster:
		//	"{" ("header" header=STRING)? "row" row=INT "column" column=INT ("colspan" colspan=INT)? ("rowspan" rowspan=INT)?
		//	colors+=Color* widgets+=Widget* "}";
		@Override public ParserRule getRule() { return rule; }

		//"{" ("header" header=STRING)? "row" row=INT "column" column=INT ("colspan" colspan=INT)? ("rowspan" rowspan=INT)?
		//colors+=Color* widgets+=Widget* "}"
		public Group getGroup() { return cGroup; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }

		//("header" header=STRING)?
		public Group getGroup_1() { return cGroup_1; }

		//"header"
		public Keyword getHeaderKeyword_1_0() { return cHeaderKeyword_1_0; }

		//header=STRING
		public Assignment getHeaderAssignment_1_1() { return cHeaderAssignment_1_1; }

		//STRING
		public RuleCall getHeaderSTRINGTerminalRuleCall_1_1_0() { return cHeaderSTRINGTerminalRuleCall_1_1_0; }

		//"row"
		public Keyword getRowKeyword_2() { return cRowKeyword_2; }

		//row=INT
		public Assignment getRowAssignment_3() { return cRowAssignment_3; }

		//INT
		public RuleCall getRowINTTerminalRuleCall_3_0() { return cRowINTTerminalRuleCall_3_0; }

		//"column"
		public Keyword getColumnKeyword_4() { return cColumnKeyword_4; }

		//column=INT
		public Assignment getColumnAssignment_5() { return cColumnAssignment_5; }

		//INT
		public RuleCall getColumnINTTerminalRuleCall_5_0() { return cColumnINTTerminalRuleCall_5_0; }

		//("colspan" colspan=INT)?
		public Group getGroup_6() { return cGroup_6; }

		//"colspan"
		public Keyword getColspanKeyword_6_0() { return cColspanKeyword_6_0; }

		//colspan=INT
		public Assignment getColspanAssignment_6_1() { return cColspanAssignment_6_1; }

		//INT
		public RuleCall getColspanINTTerminalRuleCall_6_1_0() { return cColspanINTTerminalRuleCall_6_1_0; }

		//("rowspan" rowspan=INT)?
		public Group getGroup_7() { return cGroup_7; }

		//"rowspan"
		public Keyword getRowspanKeyword_7_0() { return cRowspanKeyword_7_0; }

		//rowspan=INT
		public Assignment getRowspanAssignment_7_1() { return cRowspanAssignment_7_1; }

		//INT
		public RuleCall getRowspanINTTerminalRuleCall_7_1_0() { return cRowspanINTTerminalRuleCall_7_1_0; }

		//colors+=Color*
		public Assignment getColorsAssignment_8() { return cColorsAssignment_8; }

		//Color
		public RuleCall getColorsColorParserRuleCall_8_0() { return cColorsColorParserRuleCall_8_0; }

		//widgets+=Widget*
		public Assignment getWidgetsAssignment_9() { return cWidgetsAssignment_9; }

		//Widget
		public RuleCall getWidgetsWidgetParserRuleCall_9_0() { return cWidgetsWidgetParserRuleCall_9_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}

	public class WidgetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Widget");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cButtonParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cLabelParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSimpleClockParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cSymbolParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cCalviewParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cSimpleChartParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//Widget:
		//	Button | Label | SimpleClock | Symbol | Calview | SimpleChart;
		@Override public ParserRule getRule() { return rule; }

		//Button | Label | SimpleClock | Symbol | Calview | SimpleChart
		public Alternatives getAlternatives() { return cAlternatives; }

		//Button
		public RuleCall getButtonParserRuleCall_0() { return cButtonParserRuleCall_0; }

		//Label
		public RuleCall getLabelParserRuleCall_1() { return cLabelParserRuleCall_1; }

		//SimpleClock
		public RuleCall getSimpleClockParserRuleCall_2() { return cSimpleClockParserRuleCall_2; }

		//Symbol
		public RuleCall getSymbolParserRuleCall_3() { return cSymbolParserRuleCall_3; }

		//Calview
		public RuleCall getCalviewParserRuleCall_4() { return cCalviewParserRuleCall_4; }

		//SimpleChart
		public RuleCall getSimpleChartParserRuleCall_5() { return cSimpleChartParserRuleCall_5; }
	}

	public class DivElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Div");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDivKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cClassKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cClassAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cClassSTRINGTerminalRuleCall_3_0 = (RuleCall)cClassAssignment_3.eContents().get(0);
		private final Assignment cWidgetsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cWidgetsWidgetParserRuleCall_4_0 = (RuleCall)cWidgetsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Div:
		//	"div" "{" "class" class=STRING widgets+=Widget* "}";
		@Override public ParserRule getRule() { return rule; }

		//"div" "{" "class" class=STRING widgets+=Widget* "}"
		public Group getGroup() { return cGroup; }

		//"div"
		public Keyword getDivKeyword_0() { return cDivKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"class"
		public Keyword getClassKeyword_2() { return cClassKeyword_2; }

		//class=STRING
		public Assignment getClassAssignment_3() { return cClassAssignment_3; }

		//STRING
		public RuleCall getClassSTRINGTerminalRuleCall_3_0() { return cClassSTRINGTerminalRuleCall_3_0; }

		//widgets+=Widget*
		public Assignment getWidgetsAssignment_4() { return cWidgetsAssignment_4; }

		//Widget
		public RuleCall getWidgetsWidgetParserRuleCall_4_0() { return cWidgetsWidgetParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class CalviewElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Calview");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCalviewKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cDeviceAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDeviceSTRINGTerminalRuleCall_2_0 = (RuleCall)cDeviceAssignment_2.eContents().get(0);
		private final Keyword cGetKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cGetAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cGetSTRINGTerminalRuleCall_4_0 = (RuleCall)cGetAssignment_4.eContents().get(0);
		private final Keyword cMaxKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cMaxAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cMaxINTTerminalRuleCall_6_0 = (RuleCall)cMaxAssignment_6.eContents().get(0);
		private final Keyword cClassKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cClassAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cClassSTRINGTerminalRuleCall_8_0 = (RuleCall)cClassAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cAllForecastColorKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cAllFCAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cAllFCColorCrossReference_9_1_0 = (CrossReference)cAllFCAssignment_9_1.eContents().get(0);
		private final RuleCall cAllFCColorIDTerminalRuleCall_9_1_0_1 = (RuleCall)cAllFCColorCrossReference_9_1_0.eContents().get(1);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cAllTodayColorKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cAllTCAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cAllTCColorCrossReference_10_1_0 = (CrossReference)cAllTCAssignment_10_1.eContents().get(0);
		private final RuleCall cAllTCColorIDTerminalRuleCall_10_1_0_1 = (RuleCall)cAllTCColorCrossReference_10_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Calview:
		//	"calview" "{" device=STRING "get" get=STRING "max" max=INT "class" class=STRING ("all-forecast-color" allFC=[Color])?
		//	("all-today-color" allTC=[Color])? "}";
		@Override public ParserRule getRule() { return rule; }

		//"calview" "{" device=STRING "get" get=STRING "max" max=INT "class" class=STRING ("all-forecast-color" allFC=[Color])?
		//("all-today-color" allTC=[Color])? "}"
		public Group getGroup() { return cGroup; }

		//"calview"
		public Keyword getCalviewKeyword_0() { return cCalviewKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//device=STRING
		public Assignment getDeviceAssignment_2() { return cDeviceAssignment_2; }

		//STRING
		public RuleCall getDeviceSTRINGTerminalRuleCall_2_0() { return cDeviceSTRINGTerminalRuleCall_2_0; }

		//"get"
		public Keyword getGetKeyword_3() { return cGetKeyword_3; }

		//get=STRING
		public Assignment getGetAssignment_4() { return cGetAssignment_4; }

		//STRING
		public RuleCall getGetSTRINGTerminalRuleCall_4_0() { return cGetSTRINGTerminalRuleCall_4_0; }

		//"max"
		public Keyword getMaxKeyword_5() { return cMaxKeyword_5; }

		//max=INT
		public Assignment getMaxAssignment_6() { return cMaxAssignment_6; }

		//INT
		public RuleCall getMaxINTTerminalRuleCall_6_0() { return cMaxINTTerminalRuleCall_6_0; }

		//"class"
		public Keyword getClassKeyword_7() { return cClassKeyword_7; }

		//class=STRING
		public Assignment getClassAssignment_8() { return cClassAssignment_8; }

		//STRING
		public RuleCall getClassSTRINGTerminalRuleCall_8_0() { return cClassSTRINGTerminalRuleCall_8_0; }

		//("all-forecast-color" allFC=[Color])?
		public Group getGroup_9() { return cGroup_9; }

		//"all-forecast-color"
		public Keyword getAllForecastColorKeyword_9_0() { return cAllForecastColorKeyword_9_0; }

		//allFC=[Color]
		public Assignment getAllFCAssignment_9_1() { return cAllFCAssignment_9_1; }

		//[Color]
		public CrossReference getAllFCColorCrossReference_9_1_0() { return cAllFCColorCrossReference_9_1_0; }

		//ID
		public RuleCall getAllFCColorIDTerminalRuleCall_9_1_0_1() { return cAllFCColorIDTerminalRuleCall_9_1_0_1; }

		//("all-today-color" allTC=[Color])?
		public Group getGroup_10() { return cGroup_10; }

		//"all-today-color"
		public Keyword getAllTodayColorKeyword_10_0() { return cAllTodayColorKeyword_10_0; }

		//allTC=[Color]
		public Assignment getAllTCAssignment_10_1() { return cAllTCAssignment_10_1; }

		//[Color]
		public CrossReference getAllTCColorCrossReference_10_1_0() { return cAllTCColorCrossReference_10_1_0; }

		//ID
		public RuleCall getAllTCColorIDTerminalRuleCall_10_1_0_1() { return cAllTCColorIDTerminalRuleCall_10_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}

	public class ButtonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Button");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cButtonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdIDTerminalRuleCall_2_0 = (RuleCall)cIdAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cUrlKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cUrlAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cUrlPageCrossReference_3_1_0 = (CrossReference)cUrlAssignment_3_1.eContents().get(0);
		private final RuleCall cUrlPageIDTerminalRuleCall_3_1_0_1 = (RuleCall)cUrlPageCrossReference_3_1_0.eContents().get(1);
		private final Keyword cIconKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cIconAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cIconSTRINGTerminalRuleCall_5_0 = (RuleCall)cIconAssignment_5.eContents().get(0);
		private final Keyword cClassKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cClassAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cClassSTRINGTerminalRuleCall_7_0 = (RuleCall)cClassAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cColorKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cColorAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final CrossReference cColorColorCrossReference_8_1_0 = (CrossReference)cColorAssignment_8_1.eContents().get(0);
		private final RuleCall cColorColorIDTerminalRuleCall_8_1_0_1 = (RuleCall)cColorColorCrossReference_8_1_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cBackgroundColorKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cBackgroundColorAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cBackgroundColorColorCrossReference_9_1_0 = (CrossReference)cBackgroundColorAssignment_9_1.eContents().get(0);
		private final RuleCall cBackgroundColorColorIDTerminalRuleCall_9_1_0_1 = (RuleCall)cBackgroundColorColorCrossReference_9_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Button:
		//	"button" "{" id=ID ("url" url=[Page])? "icon" icon=STRING "class" class=STRING ("color" color=[Color])?
		//	("background-color" backgroundColor=[Color])? "}";
		@Override public ParserRule getRule() { return rule; }

		//"button" "{" id=ID ("url" url=[Page])? "icon" icon=STRING "class" class=STRING ("color" color=[Color])?
		//("background-color" backgroundColor=[Color])? "}"
		public Group getGroup() { return cGroup; }

		//"button"
		public Keyword getButtonKeyword_0() { return cButtonKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//id=ID
		public Assignment getIdAssignment_2() { return cIdAssignment_2; }

		//ID
		public RuleCall getIdIDTerminalRuleCall_2_0() { return cIdIDTerminalRuleCall_2_0; }

		//("url" url=[Page])?
		public Group getGroup_3() { return cGroup_3; }

		//"url"
		public Keyword getUrlKeyword_3_0() { return cUrlKeyword_3_0; }

		//url=[Page]
		public Assignment getUrlAssignment_3_1() { return cUrlAssignment_3_1; }

		//[Page]
		public CrossReference getUrlPageCrossReference_3_1_0() { return cUrlPageCrossReference_3_1_0; }

		//ID
		public RuleCall getUrlPageIDTerminalRuleCall_3_1_0_1() { return cUrlPageIDTerminalRuleCall_3_1_0_1; }

		//"icon"
		public Keyword getIconKeyword_4() { return cIconKeyword_4; }

		//icon=STRING
		public Assignment getIconAssignment_5() { return cIconAssignment_5; }

		//STRING
		public RuleCall getIconSTRINGTerminalRuleCall_5_0() { return cIconSTRINGTerminalRuleCall_5_0; }

		//"class"
		public Keyword getClassKeyword_6() { return cClassKeyword_6; }

		//class=STRING
		public Assignment getClassAssignment_7() { return cClassAssignment_7; }

		//STRING
		public RuleCall getClassSTRINGTerminalRuleCall_7_0() { return cClassSTRINGTerminalRuleCall_7_0; }

		//("color" color=[Color])?
		public Group getGroup_8() { return cGroup_8; }

		//"color"
		public Keyword getColorKeyword_8_0() { return cColorKeyword_8_0; }

		//color=[Color]
		public Assignment getColorAssignment_8_1() { return cColorAssignment_8_1; }

		//[Color]
		public CrossReference getColorColorCrossReference_8_1_0() { return cColorColorCrossReference_8_1_0; }

		//ID
		public RuleCall getColorColorIDTerminalRuleCall_8_1_0_1() { return cColorColorIDTerminalRuleCall_8_1_0_1; }

		//("background-color" backgroundColor=[Color])?
		public Group getGroup_9() { return cGroup_9; }

		//"background-color"
		public Keyword getBackgroundColorKeyword_9_0() { return cBackgroundColorKeyword_9_0; }

		//backgroundColor=[Color]
		public Assignment getBackgroundColorAssignment_9_1() { return cBackgroundColorAssignment_9_1; }

		//[Color]
		public CrossReference getBackgroundColorColorCrossReference_9_1_0() { return cBackgroundColorColorCrossReference_9_1_0; }

		//ID
		public RuleCall getBackgroundColorColorIDTerminalRuleCall_9_1_0_1() { return cBackgroundColorColorIDTerminalRuleCall_9_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}

	public class SymbolElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Symbol");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSymbolKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cDeviceAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDeviceSTRINGTerminalRuleCall_2_0 = (RuleCall)cDeviceAssignment_2.eContents().get(0);
		private final Keyword cGetKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cGetAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cGetSTRINGTerminalRuleCall_4_0 = (RuleCall)cGetAssignment_4.eContents().get(0);
		private final Keyword cGetOnKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cGetOnAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cGetOnSTRINGTerminalRuleCall_6_0 = (RuleCall)cGetOnAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cGetOffKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cGetOffAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cGetOffSTRINGTerminalRuleCall_7_1_0 = (RuleCall)cGetOffAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cClassKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cClassAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cClassSTRINGTerminalRuleCall_8_1_0 = (RuleCall)cClassAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cBackgroundIconKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cBgiconAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cBgiconSTRINGTerminalRuleCall_9_1_0 = (RuleCall)cBgiconAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cBackgroundOnColorKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cOnBackGroundColorAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cOnBackGroundColorColorCrossReference_10_1_0 = (CrossReference)cOnBackGroundColorAssignment_10_1.eContents().get(0);
		private final RuleCall cOnBackGroundColorColorIDTerminalRuleCall_10_1_0_1 = (RuleCall)cOnBackGroundColorColorCrossReference_10_1_0.eContents().get(1);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cOnColorKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cOnColorAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final CrossReference cOnColorColorCrossReference_11_1_0 = (CrossReference)cOnColorAssignment_11_1.eContents().get(0);
		private final RuleCall cOnColorColorIDTerminalRuleCall_11_1_0_1 = (RuleCall)cOnColorColorCrossReference_11_1_0.eContents().get(1);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cOffColorKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cOffColorAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final CrossReference cOffColorColorCrossReference_12_1_0 = (CrossReference)cOffColorAssignment_12_1.eContents().get(0);
		private final RuleCall cOffColorColorIDTerminalRuleCall_12_1_0_1 = (RuleCall)cOffColorColorCrossReference_12_1_0.eContents().get(1);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cIconsKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_13_1 = (Keyword)cGroup_13.eContents().get(1);
		private final Assignment cIconsAssignment_13_2 = (Assignment)cGroup_13.eContents().get(2);
		private final RuleCall cIconsSTRINGTerminalRuleCall_13_2_0 = (RuleCall)cIconsAssignment_13_2.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_13_3 = (Keyword)cGroup_13.eContents().get(3);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cOnColorsKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_14_1 = (Keyword)cGroup_14.eContents().get(1);
		private final Assignment cOnColorsAssignment_14_2 = (Assignment)cGroup_14.eContents().get(2);
		private final CrossReference cOnColorsColorCrossReference_14_2_0 = (CrossReference)cOnColorsAssignment_14_2.eContents().get(0);
		private final RuleCall cOnColorsColorIDTerminalRuleCall_14_2_0_1 = (RuleCall)cOnColorsColorCrossReference_14_2_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_14_3 = (Keyword)cGroup_14.eContents().get(3);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cOnBackgroundColorsKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_15_1 = (Keyword)cGroup_15.eContents().get(1);
		private final Assignment cOnBackgroundColorsAssignment_15_2 = (Assignment)cGroup_15.eContents().get(2);
		private final CrossReference cOnBackgroundColorsColorCrossReference_15_2_0 = (CrossReference)cOnBackgroundColorsAssignment_15_2.eContents().get(0);
		private final RuleCall cOnBackgroundColorsColorIDTerminalRuleCall_15_2_0_1 = (RuleCall)cOnBackgroundColorsColorCrossReference_15_2_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_15_3 = (Keyword)cGroup_15.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		
		//Symbol:
		//	"symbol" "{" device=STRING "get" get=STRING "getOn" getOn+=STRING* ("getOff" getOff+=STRING*)? ("class" class=STRING)?
		//	("background-icon" bgicon=STRING)? ("background-on-color" onBackGroundColor=[Color])? ("on-color" onColor=[Color])?
		//	("off-color" offColor=[Color])? ("icons" "[" icons+=STRING* "]")? ("onColors" "[" onColors+=[Color]* "]")?
		//	("onBackgroundColors" "[" onBackgroundColors+=[Color]* "]")? "}";
		@Override public ParserRule getRule() { return rule; }

		//"symbol" "{" device=STRING "get" get=STRING "getOn" getOn+=STRING* ("getOff" getOff+=STRING*)? ("class" class=STRING)?
		//("background-icon" bgicon=STRING)? ("background-on-color" onBackGroundColor=[Color])? ("on-color" onColor=[Color])?
		//("off-color" offColor=[Color])? ("icons" "[" icons+=STRING* "]")? ("onColors" "[" onColors+=[Color]* "]")?
		//("onBackgroundColors" "[" onBackgroundColors+=[Color]* "]")? "}"
		public Group getGroup() { return cGroup; }

		//"symbol"
		public Keyword getSymbolKeyword_0() { return cSymbolKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//device=STRING
		public Assignment getDeviceAssignment_2() { return cDeviceAssignment_2; }

		//STRING
		public RuleCall getDeviceSTRINGTerminalRuleCall_2_0() { return cDeviceSTRINGTerminalRuleCall_2_0; }

		//"get"
		public Keyword getGetKeyword_3() { return cGetKeyword_3; }

		//get=STRING
		public Assignment getGetAssignment_4() { return cGetAssignment_4; }

		//STRING
		public RuleCall getGetSTRINGTerminalRuleCall_4_0() { return cGetSTRINGTerminalRuleCall_4_0; }

		//"getOn"
		public Keyword getGetOnKeyword_5() { return cGetOnKeyword_5; }

		//getOn+=STRING*
		public Assignment getGetOnAssignment_6() { return cGetOnAssignment_6; }

		//STRING
		public RuleCall getGetOnSTRINGTerminalRuleCall_6_0() { return cGetOnSTRINGTerminalRuleCall_6_0; }

		//("getOff" getOff+=STRING*)?
		public Group getGroup_7() { return cGroup_7; }

		//"getOff"
		public Keyword getGetOffKeyword_7_0() { return cGetOffKeyword_7_0; }

		//getOff+=STRING*
		public Assignment getGetOffAssignment_7_1() { return cGetOffAssignment_7_1; }

		//STRING
		public RuleCall getGetOffSTRINGTerminalRuleCall_7_1_0() { return cGetOffSTRINGTerminalRuleCall_7_1_0; }

		//("class" class=STRING)?
		public Group getGroup_8() { return cGroup_8; }

		//"class"
		public Keyword getClassKeyword_8_0() { return cClassKeyword_8_0; }

		//class=STRING
		public Assignment getClassAssignment_8_1() { return cClassAssignment_8_1; }

		//STRING
		public RuleCall getClassSTRINGTerminalRuleCall_8_1_0() { return cClassSTRINGTerminalRuleCall_8_1_0; }

		//("background-icon" bgicon=STRING)?
		public Group getGroup_9() { return cGroup_9; }

		//"background-icon"
		public Keyword getBackgroundIconKeyword_9_0() { return cBackgroundIconKeyword_9_0; }

		//bgicon=STRING
		public Assignment getBgiconAssignment_9_1() { return cBgiconAssignment_9_1; }

		//STRING
		public RuleCall getBgiconSTRINGTerminalRuleCall_9_1_0() { return cBgiconSTRINGTerminalRuleCall_9_1_0; }

		//("background-on-color" onBackGroundColor=[Color])?
		public Group getGroup_10() { return cGroup_10; }

		//"background-on-color"
		public Keyword getBackgroundOnColorKeyword_10_0() { return cBackgroundOnColorKeyword_10_0; }

		//onBackGroundColor=[Color]
		public Assignment getOnBackGroundColorAssignment_10_1() { return cOnBackGroundColorAssignment_10_1; }

		//[Color]
		public CrossReference getOnBackGroundColorColorCrossReference_10_1_0() { return cOnBackGroundColorColorCrossReference_10_1_0; }

		//ID
		public RuleCall getOnBackGroundColorColorIDTerminalRuleCall_10_1_0_1() { return cOnBackGroundColorColorIDTerminalRuleCall_10_1_0_1; }

		//("on-color" onColor=[Color])?
		public Group getGroup_11() { return cGroup_11; }

		//"on-color"
		public Keyword getOnColorKeyword_11_0() { return cOnColorKeyword_11_0; }

		//onColor=[Color]
		public Assignment getOnColorAssignment_11_1() { return cOnColorAssignment_11_1; }

		//[Color]
		public CrossReference getOnColorColorCrossReference_11_1_0() { return cOnColorColorCrossReference_11_1_0; }

		//ID
		public RuleCall getOnColorColorIDTerminalRuleCall_11_1_0_1() { return cOnColorColorIDTerminalRuleCall_11_1_0_1; }

		//("off-color" offColor=[Color])?
		public Group getGroup_12() { return cGroup_12; }

		//"off-color"
		public Keyword getOffColorKeyword_12_0() { return cOffColorKeyword_12_0; }

		//offColor=[Color]
		public Assignment getOffColorAssignment_12_1() { return cOffColorAssignment_12_1; }

		//[Color]
		public CrossReference getOffColorColorCrossReference_12_1_0() { return cOffColorColorCrossReference_12_1_0; }

		//ID
		public RuleCall getOffColorColorIDTerminalRuleCall_12_1_0_1() { return cOffColorColorIDTerminalRuleCall_12_1_0_1; }

		//("icons" "[" icons+=STRING* "]")?
		public Group getGroup_13() { return cGroup_13; }

		//"icons"
		public Keyword getIconsKeyword_13_0() { return cIconsKeyword_13_0; }

		//"["
		public Keyword getLeftSquareBracketKeyword_13_1() { return cLeftSquareBracketKeyword_13_1; }

		//icons+=STRING*
		public Assignment getIconsAssignment_13_2() { return cIconsAssignment_13_2; }

		//STRING
		public RuleCall getIconsSTRINGTerminalRuleCall_13_2_0() { return cIconsSTRINGTerminalRuleCall_13_2_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_13_3() { return cRightSquareBracketKeyword_13_3; }

		//("onColors" "[" onColors+=[Color]* "]")?
		public Group getGroup_14() { return cGroup_14; }

		//"onColors"
		public Keyword getOnColorsKeyword_14_0() { return cOnColorsKeyword_14_0; }

		//"["
		public Keyword getLeftSquareBracketKeyword_14_1() { return cLeftSquareBracketKeyword_14_1; }

		//onColors+=[Color]*
		public Assignment getOnColorsAssignment_14_2() { return cOnColorsAssignment_14_2; }

		//[Color]
		public CrossReference getOnColorsColorCrossReference_14_2_0() { return cOnColorsColorCrossReference_14_2_0; }

		//ID
		public RuleCall getOnColorsColorIDTerminalRuleCall_14_2_0_1() { return cOnColorsColorIDTerminalRuleCall_14_2_0_1; }

		//"]"
		public Keyword getRightSquareBracketKeyword_14_3() { return cRightSquareBracketKeyword_14_3; }

		//("onBackgroundColors" "[" onBackgroundColors+=[Color]* "]")?
		public Group getGroup_15() { return cGroup_15; }

		//"onBackgroundColors"
		public Keyword getOnBackgroundColorsKeyword_15_0() { return cOnBackgroundColorsKeyword_15_0; }

		//"["
		public Keyword getLeftSquareBracketKeyword_15_1() { return cLeftSquareBracketKeyword_15_1; }

		//onBackgroundColors+=[Color]*
		public Assignment getOnBackgroundColorsAssignment_15_2() { return cOnBackgroundColorsAssignment_15_2; }

		//[Color]
		public CrossReference getOnBackgroundColorsColorCrossReference_15_2_0() { return cOnBackgroundColorsColorCrossReference_15_2_0; }

		//ID
		public RuleCall getOnBackgroundColorsColorIDTerminalRuleCall_15_2_0_1() { return cOnBackgroundColorsColorIDTerminalRuleCall_15_2_0_1; }

		//"]"
		public Keyword getRightSquareBracketKeyword_15_3() { return cRightSquareBracketKeyword_15_3; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }
	}

	public class SimpleClockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SimpleClock");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSimpleClockKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIdAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIdIDTerminalRuleCall_2_0 = (RuleCall)cIdAssignment_2.eContents().get(0);
		private final Keyword cDateFormatKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDateFormatAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDateFormatSTRINGTerminalRuleCall_4_0 = (RuleCall)cDateFormatAssignment_4.eContents().get(0);
		private final Keyword cTimeFormatKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTimeFormatAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTimeFormatSTRINGTerminalRuleCall_6_0 = (RuleCall)cTimeFormatAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cDateColorKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cDateColorAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cDateColorColorCrossReference_7_1_0 = (CrossReference)cDateColorAssignment_7_1.eContents().get(0);
		private final RuleCall cDateColorColorIDTerminalRuleCall_7_1_0_1 = (RuleCall)cDateColorColorCrossReference_7_1_0.eContents().get(1);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cTimeColorKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cTimeColorAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final CrossReference cTimeColorColorCrossReference_8_1_0 = (CrossReference)cTimeColorAssignment_8_1.eContents().get(0);
		private final RuleCall cTimeColorColorIDTerminalRuleCall_8_1_0_1 = (RuleCall)cTimeColorColorCrossReference_8_1_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cClassKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cClassAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cClassSTRINGTerminalRuleCall_9_1_0 = (RuleCall)cClassAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cStyleKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cStyleAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cStyleSTRINGTerminalRuleCall_10_1_0 = (RuleCall)cStyleAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cBgColorsKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cBgColorsAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final CrossReference cBgColorsColorCrossReference_11_1_0 = (CrossReference)cBgColorsAssignment_11_1.eContents().get(0);
		private final RuleCall cBgColorsColorIDTerminalRuleCall_11_1_0_1 = (RuleCall)cBgColorsColorCrossReference_11_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//SimpleClock:
		//	"SimpleClock" "{" id=ID? "date-format" dateFormat=STRING "time-format" timeFormat=STRING ("date-color"
		//	dateColor=[Color])? ("time-color" timeColor=[Color])? ("class" class=STRING)? ("style" style=STRING)? ("bg-colors"
		//	bgColors+=[Color])* "}";
		@Override public ParserRule getRule() { return rule; }

		//"SimpleClock" "{" id=ID? "date-format" dateFormat=STRING "time-format" timeFormat=STRING ("date-color"
		//dateColor=[Color])? ("time-color" timeColor=[Color])? ("class" class=STRING)? ("style" style=STRING)? ("bg-colors"
		//bgColors+=[Color])* "}"
		public Group getGroup() { return cGroup; }

		//"SimpleClock"
		public Keyword getSimpleClockKeyword_0() { return cSimpleClockKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//id=ID?
		public Assignment getIdAssignment_2() { return cIdAssignment_2; }

		//ID
		public RuleCall getIdIDTerminalRuleCall_2_0() { return cIdIDTerminalRuleCall_2_0; }

		//"date-format"
		public Keyword getDateFormatKeyword_3() { return cDateFormatKeyword_3; }

		//dateFormat=STRING
		public Assignment getDateFormatAssignment_4() { return cDateFormatAssignment_4; }

		//STRING
		public RuleCall getDateFormatSTRINGTerminalRuleCall_4_0() { return cDateFormatSTRINGTerminalRuleCall_4_0; }

		//"time-format"
		public Keyword getTimeFormatKeyword_5() { return cTimeFormatKeyword_5; }

		//timeFormat=STRING
		public Assignment getTimeFormatAssignment_6() { return cTimeFormatAssignment_6; }

		//STRING
		public RuleCall getTimeFormatSTRINGTerminalRuleCall_6_0() { return cTimeFormatSTRINGTerminalRuleCall_6_0; }

		//("date-color" dateColor=[Color])?
		public Group getGroup_7() { return cGroup_7; }

		//"date-color"
		public Keyword getDateColorKeyword_7_0() { return cDateColorKeyword_7_0; }

		//dateColor=[Color]
		public Assignment getDateColorAssignment_7_1() { return cDateColorAssignment_7_1; }

		//[Color]
		public CrossReference getDateColorColorCrossReference_7_1_0() { return cDateColorColorCrossReference_7_1_0; }

		//ID
		public RuleCall getDateColorColorIDTerminalRuleCall_7_1_0_1() { return cDateColorColorIDTerminalRuleCall_7_1_0_1; }

		//("time-color" timeColor=[Color])?
		public Group getGroup_8() { return cGroup_8; }

		//"time-color"
		public Keyword getTimeColorKeyword_8_0() { return cTimeColorKeyword_8_0; }

		//timeColor=[Color]
		public Assignment getTimeColorAssignment_8_1() { return cTimeColorAssignment_8_1; }

		//[Color]
		public CrossReference getTimeColorColorCrossReference_8_1_0() { return cTimeColorColorCrossReference_8_1_0; }

		//ID
		public RuleCall getTimeColorColorIDTerminalRuleCall_8_1_0_1() { return cTimeColorColorIDTerminalRuleCall_8_1_0_1; }

		//("class" class=STRING)?
		public Group getGroup_9() { return cGroup_9; }

		//"class"
		public Keyword getClassKeyword_9_0() { return cClassKeyword_9_0; }

		//class=STRING
		public Assignment getClassAssignment_9_1() { return cClassAssignment_9_1; }

		//STRING
		public RuleCall getClassSTRINGTerminalRuleCall_9_1_0() { return cClassSTRINGTerminalRuleCall_9_1_0; }

		//("style" style=STRING)?
		public Group getGroup_10() { return cGroup_10; }

		//"style"
		public Keyword getStyleKeyword_10_0() { return cStyleKeyword_10_0; }

		//style=STRING
		public Assignment getStyleAssignment_10_1() { return cStyleAssignment_10_1; }

		//STRING
		public RuleCall getStyleSTRINGTerminalRuleCall_10_1_0() { return cStyleSTRINGTerminalRuleCall_10_1_0; }

		//("bg-colors" bgColors+=[Color])*
		public Group getGroup_11() { return cGroup_11; }

		//"bg-colors"
		public Keyword getBgColorsKeyword_11_0() { return cBgColorsKeyword_11_0; }

		//bgColors+=[Color]
		public Assignment getBgColorsAssignment_11_1() { return cBgColorsAssignment_11_1; }

		//[Color]
		public CrossReference getBgColorsColorCrossReference_11_1_0() { return cBgColorsColorCrossReference_11_1_0; }

		//ID
		public RuleCall getBgColorsColorIDTerminalRuleCall_11_1_0_1() { return cBgColorsColorIDTerminalRuleCall_11_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}

	public class SimpleChartElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SimpleChart");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSimpleChartKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cDeviceAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDeviceSTRINGTerminalRuleCall_2_0 = (RuleCall)cDeviceAssignment_2.eContents().get(0);
		private final Keyword cLogConfigKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cLog_deviceAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cLog_deviceSTRINGTerminalRuleCall_4_0 = (RuleCall)cLog_deviceAssignment_4.eContents().get(0);
		private final Assignment cLogfileAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cLogfileSTRINGTerminalRuleCall_5_0 = (RuleCall)cLogfileAssignment_5.eContents().get(0);
		private final Keyword cColumnSpecKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cColumnSpecAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cColumnSpecSTRINGTerminalRuleCall_7_0 = (RuleCall)cColumnSpecAssignment_7.eContents().get(0);
		private final Keyword cMinValueKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cMinAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cMinSTRINGTerminalRuleCall_9_0 = (RuleCall)cMinAssignment_9.eContents().get(0);
		private final Keyword cMaxValueKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cMaxAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cMaxSTRINGTerminalRuleCall_11_0 = (RuleCall)cMaxAssignment_11.eContents().get(0);
		private final Keyword cXTicksKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cXTicksAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cXTicksINTTerminalRuleCall_13_0 = (RuleCall)cXTicksAssignment_13.eContents().get(0);
		private final Keyword cYTicksKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Assignment cYTicksAssignment_15 = (Assignment)cGroup.eContents().get(15);
		private final RuleCall cYTicksINTTerminalRuleCall_15_0 = (RuleCall)cYTicksAssignment_15.eContents().get(0);
		private final Keyword cDaysagoKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cDaysagoAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cDaysagoINTTerminalRuleCall_17_0 = (RuleCall)cDaysagoAssignment_17.eContents().get(0);
		private final Keyword cClassKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Assignment cClassAssignment_19 = (Assignment)cGroup.eContents().get(19);
		private final RuleCall cClassSTRINGTerminalRuleCall_19_0 = (RuleCall)cClassAssignment_19.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_20 = (Keyword)cGroup.eContents().get(20);
		
		//SimpleChart:
		//	"simpleChart" "{" device=STRING "log-config" log_device=STRING logfile=STRING "columnSpec" columnSpec=STRING
		//	"minValue" min=STRING "maxValue" max=STRING "xTicks" xTicks=INT "yTicks" yTicks=INT "daysago" daysago=INT "class"
		//	class=STRING "}";
		@Override public ParserRule getRule() { return rule; }

		//"simpleChart" "{" device=STRING "log-config" log_device=STRING logfile=STRING "columnSpec" columnSpec=STRING "minValue"
		//min=STRING "maxValue" max=STRING "xTicks" xTicks=INT "yTicks" yTicks=INT "daysago" daysago=INT "class" class=STRING "}"
		public Group getGroup() { return cGroup; }

		//"simpleChart"
		public Keyword getSimpleChartKeyword_0() { return cSimpleChartKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//device=STRING
		public Assignment getDeviceAssignment_2() { return cDeviceAssignment_2; }

		//STRING
		public RuleCall getDeviceSTRINGTerminalRuleCall_2_0() { return cDeviceSTRINGTerminalRuleCall_2_0; }

		//"log-config"
		public Keyword getLogConfigKeyword_3() { return cLogConfigKeyword_3; }

		//log_device=STRING
		public Assignment getLog_deviceAssignment_4() { return cLog_deviceAssignment_4; }

		//STRING
		public RuleCall getLog_deviceSTRINGTerminalRuleCall_4_0() { return cLog_deviceSTRINGTerminalRuleCall_4_0; }

		//logfile=STRING
		public Assignment getLogfileAssignment_5() { return cLogfileAssignment_5; }

		//STRING
		public RuleCall getLogfileSTRINGTerminalRuleCall_5_0() { return cLogfileSTRINGTerminalRuleCall_5_0; }

		//"columnSpec"
		public Keyword getColumnSpecKeyword_6() { return cColumnSpecKeyword_6; }

		//columnSpec=STRING
		public Assignment getColumnSpecAssignment_7() { return cColumnSpecAssignment_7; }

		//STRING
		public RuleCall getColumnSpecSTRINGTerminalRuleCall_7_0() { return cColumnSpecSTRINGTerminalRuleCall_7_0; }

		//"minValue"
		public Keyword getMinValueKeyword_8() { return cMinValueKeyword_8; }

		//min=STRING
		public Assignment getMinAssignment_9() { return cMinAssignment_9; }

		//STRING
		public RuleCall getMinSTRINGTerminalRuleCall_9_0() { return cMinSTRINGTerminalRuleCall_9_0; }

		//"maxValue"
		public Keyword getMaxValueKeyword_10() { return cMaxValueKeyword_10; }

		//max=STRING
		public Assignment getMaxAssignment_11() { return cMaxAssignment_11; }

		//STRING
		public RuleCall getMaxSTRINGTerminalRuleCall_11_0() { return cMaxSTRINGTerminalRuleCall_11_0; }

		//"xTicks"
		public Keyword getXTicksKeyword_12() { return cXTicksKeyword_12; }

		//xTicks=INT
		public Assignment getXTicksAssignment_13() { return cXTicksAssignment_13; }

		//INT
		public RuleCall getXTicksINTTerminalRuleCall_13_0() { return cXTicksINTTerminalRuleCall_13_0; }

		//"yTicks"
		public Keyword getYTicksKeyword_14() { return cYTicksKeyword_14; }

		//yTicks=INT
		public Assignment getYTicksAssignment_15() { return cYTicksAssignment_15; }

		//INT
		public RuleCall getYTicksINTTerminalRuleCall_15_0() { return cYTicksINTTerminalRuleCall_15_0; }

		//"daysago"
		public Keyword getDaysagoKeyword_16() { return cDaysagoKeyword_16; }

		//daysago=INT
		public Assignment getDaysagoAssignment_17() { return cDaysagoAssignment_17; }

		//INT
		public RuleCall getDaysagoINTTerminalRuleCall_17_0() { return cDaysagoINTTerminalRuleCall_17_0; }

		//"class"
		public Keyword getClassKeyword_18() { return cClassKeyword_18; }

		//class=STRING
		public Assignment getClassAssignment_19() { return cClassAssignment_19; }

		//STRING
		public RuleCall getClassSTRINGTerminalRuleCall_19_0() { return cClassSTRINGTerminalRuleCall_19_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_20() { return cRightCurlyBracketKeyword_20; }
	}

	public class ColorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Color");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cColorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cRgbAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRgbSTRINGTerminalRuleCall_2_0 = (RuleCall)cRgbAssignment_2.eContents().get(0);
		
		//Color:
		//	"color" name=ID rgb=STRING;
		@Override public ParserRule getRule() { return rule; }

		//"color" name=ID rgb=STRING
		public Group getGroup() { return cGroup; }

		//"color"
		public Keyword getColorKeyword_0() { return cColorKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//rgb=STRING
		public Assignment getRgbAssignment_2() { return cRgbAssignment_2; }

		//STRING
		public RuleCall getRgbSTRINGTerminalRuleCall_2_0() { return cRgbSTRINGTerminalRuleCall_2_0; }
	}

	public class LabelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Label");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLabelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Label:
		//	"label {" id=ID "}";
		@Override public ParserRule getRule() { return rule; }

		//"label {" id=ID "}"
		public Group getGroup() { return cGroup; }

		//"label {"
		public Keyword getLabelKeyword_0() { return cLabelKeyword_0; }

		//id=ID
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }

		//ID
		public RuleCall getIdIDTerminalRuleCall_1_0() { return cIdIDTerminalRuleCall_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2() { return cRightCurlyBracketKeyword_2; }
	}
	
	
	private final TabletUIElements pTabletUI;
	private final SettingsElements pSettings;
	private final SettingsElementElements pSettingsElement;
	private final CSSElements pCSS;
	private final AbstractElementElements pAbstractElement;
	private final BOOLElements pBOOL;
	private final PageElements pPage;
	private final GridsterElements pGridster;
	private final WidgetElements pWidget;
	private final DivElements pDiv;
	private final CalviewElements pCalview;
	private final ButtonElements pButton;
	private final SymbolElements pSymbol;
	private final SimpleClockElements pSimpleClock;
	private final SimpleChartElements pSimpleChart;
	private final ColorElements pColor;
	private final LabelElements pLabel;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public TabletUIDSLGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pTabletUI = new TabletUIElements();
		this.pSettings = new SettingsElements();
		this.pSettingsElement = new SettingsElementElements();
		this.pCSS = new CSSElements();
		this.pAbstractElement = new AbstractElementElements();
		this.pBOOL = new BOOLElements();
		this.pPage = new PageElements();
		this.pGridster = new GridsterElements();
		this.pWidget = new WidgetElements();
		this.pDiv = new DivElements();
		this.pCalview = new CalviewElements();
		this.pButton = new ButtonElements();
		this.pSymbol = new SymbolElements();
		this.pSimpleClock = new SimpleClockElements();
		this.pSimpleChart = new SimpleChartElements();
		this.pColor = new ColorElements();
		this.pLabel = new LabelElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.ckr.TabletUIDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//TabletUI:
	//	settings=Settings elements+=AbstractElement*;
	public TabletUIElements getTabletUIAccess() {
		return pTabletUI;
	}
	
	public ParserRule getTabletUIRule() {
		return getTabletUIAccess().getRule();
	}

	//Settings:
	//	"settings" "title" title=STRING ("fhemweb_url" fhemweb_url=STRING)? "width" width=INT "height" height=INT "columns"
	//	columns=INT "rows" rows=INT ("debug" debug=BOOL)? "drag&drop" dragdrop=BOOL "gridster_margin" margin=INT
	//	settings+=SettingsElement*;
	public SettingsElements getSettingsAccess() {
		return pSettings;
	}
	
	public ParserRule getSettingsRule() {
		return getSettingsAccess().getRule();
	}

	//SettingsElement:
	//	CSS | Color;
	public SettingsElementElements getSettingsElementAccess() {
		return pSettingsElement;
	}
	
	public ParserRule getSettingsElementRule() {
		return getSettingsElementAccess().getRule();
	}

	//CSS:
	//	"css" path=STRING;
	public CSSElements getCSSAccess() {
		return pCSS;
	}
	
	public ParserRule getCSSRule() {
		return getCSSAccess().getRule();
	}

	//AbstractElement:
	//	Page;
	public AbstractElementElements getAbstractElementAccess() {
		return pAbstractElement;
	}
	
	public ParserRule getAbstractElementRule() {
		return getAbstractElementAccess().getRule();
	}

	//BOOL:
	//	"true" | "false";
	public BOOLElements getBOOLAccess() {
		return pBOOL;
	}
	
	public ParserRule getBOOLRule() {
		return getBOOLAccess().getRule();
	}

	//Page:
	//	name=ID "{" elements+=Gridster* "}";
	public PageElements getPageAccess() {
		return pPage;
	}
	
	public ParserRule getPageRule() {
		return getPageAccess().getRule();
	}

	//Gridster:
	//	"{" ("header" header=STRING)? "row" row=INT "column" column=INT ("colspan" colspan=INT)? ("rowspan" rowspan=INT)?
	//	colors+=Color* widgets+=Widget* "}";
	public GridsterElements getGridsterAccess() {
		return pGridster;
	}
	
	public ParserRule getGridsterRule() {
		return getGridsterAccess().getRule();
	}

	//Widget:
	//	Button | Label | SimpleClock | Symbol | Calview | SimpleChart;
	public WidgetElements getWidgetAccess() {
		return pWidget;
	}
	
	public ParserRule getWidgetRule() {
		return getWidgetAccess().getRule();
	}

	//Div:
	//	"div" "{" "class" class=STRING widgets+=Widget* "}";
	public DivElements getDivAccess() {
		return pDiv;
	}
	
	public ParserRule getDivRule() {
		return getDivAccess().getRule();
	}

	//Calview:
	//	"calview" "{" device=STRING "get" get=STRING "max" max=INT "class" class=STRING ("all-forecast-color" allFC=[Color])?
	//	("all-today-color" allTC=[Color])? "}";
	public CalviewElements getCalviewAccess() {
		return pCalview;
	}
	
	public ParserRule getCalviewRule() {
		return getCalviewAccess().getRule();
	}

	//Button:
	//	"button" "{" id=ID ("url" url=[Page])? "icon" icon=STRING "class" class=STRING ("color" color=[Color])?
	//	("background-color" backgroundColor=[Color])? "}";
	public ButtonElements getButtonAccess() {
		return pButton;
	}
	
	public ParserRule getButtonRule() {
		return getButtonAccess().getRule();
	}

	//Symbol:
	//	"symbol" "{" device=STRING "get" get=STRING "getOn" getOn+=STRING* ("getOff" getOff+=STRING*)? ("class" class=STRING)?
	//	("background-icon" bgicon=STRING)? ("background-on-color" onBackGroundColor=[Color])? ("on-color" onColor=[Color])?
	//	("off-color" offColor=[Color])? ("icons" "[" icons+=STRING* "]")? ("onColors" "[" onColors+=[Color]* "]")?
	//	("onBackgroundColors" "[" onBackgroundColors+=[Color]* "]")? "}";
	public SymbolElements getSymbolAccess() {
		return pSymbol;
	}
	
	public ParserRule getSymbolRule() {
		return getSymbolAccess().getRule();
	}

	//SimpleClock:
	//	"SimpleClock" "{" id=ID? "date-format" dateFormat=STRING "time-format" timeFormat=STRING ("date-color"
	//	dateColor=[Color])? ("time-color" timeColor=[Color])? ("class" class=STRING)? ("style" style=STRING)? ("bg-colors"
	//	bgColors+=[Color])* "}";
	public SimpleClockElements getSimpleClockAccess() {
		return pSimpleClock;
	}
	
	public ParserRule getSimpleClockRule() {
		return getSimpleClockAccess().getRule();
	}

	//SimpleChart:
	//	"simpleChart" "{" device=STRING "log-config" log_device=STRING logfile=STRING "columnSpec" columnSpec=STRING
	//	"minValue" min=STRING "maxValue" max=STRING "xTicks" xTicks=INT "yTicks" yTicks=INT "daysago" daysago=INT "class"
	//	class=STRING "}";
	public SimpleChartElements getSimpleChartAccess() {
		return pSimpleChart;
	}
	
	public ParserRule getSimpleChartRule() {
		return getSimpleChartAccess().getRule();
	}

	//Color:
	//	"color" name=ID rgb=STRING;
	public ColorElements getColorAccess() {
		return pColor;
	}
	
	public ParserRule getColorRule() {
		return getColorAccess().getRule();
	}

	//Label:
	//	"label {" id=ID "}";
	public LabelElements getLabelAccess() {
		return pLabel;
	}
	
	public ParserRule getLabelRule() {
		return getLabelAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
