/*
 * generated by Xtext
 */
package org.ckr.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.ckr.services.TabletUIDSLGrammarAccess;

public class TabletUIDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private TabletUIDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.ckr.ui.contentassist.antlr.internal.InternalTabletUIDSLParser createParser() {
		org.ckr.ui.contentassist.antlr.internal.InternalTabletUIDSLParser result = new org.ckr.ui.contentassist.antlr.internal.InternalTabletUIDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSettingsElementAccess().getAlternatives(), "rule__SettingsElement__Alternatives");
					put(grammarAccess.getAbstractElementAccess().getAlternatives(), "rule__AbstractElement__Alternatives");
					put(grammarAccess.getBOOLAccess().getAlternatives(), "rule__BOOL__Alternatives");
					put(grammarAccess.getWidgetDefAccess().getAlternatives(), "rule__WidgetDef__Alternatives");
					put(grammarAccess.getWidgetAccess().getAlternatives(), "rule__Widget__Alternatives");
					put(grammarAccess.getWeatherImageSetAccess().getAlternatives(), "rule__WeatherImageSet__Alternatives");
					put(grammarAccess.getButtonUrlAccess().getAlternatives(), "rule__ButtonUrl__Alternatives");
					put(grammarAccess.getTabletUIAccess().getGroup(), "rule__TabletUI__Group__0");
					put(grammarAccess.getSettingsAccess().getGroup(), "rule__Settings__Group__0");
					put(grammarAccess.getSettingsAccess().getGroup_3(), "rule__Settings__Group_3__0");
					put(grammarAccess.getSettingsAccess().getGroup_12(), "rule__Settings__Group_12__0");
					put(grammarAccess.getCSSAccess().getGroup(), "rule__CSS__Group__0");
					put(grammarAccess.getPageAccess().getGroup(), "rule__Page__Group__0");
					put(grammarAccess.getPageAccess().getGroup_2(), "rule__Page__Group_2__0");
					put(grammarAccess.getScreensaverAccess().getGroup(), "rule__Screensaver__Group__0");
					put(grammarAccess.getTemplateAccess().getGroup(), "rule__Template__Group__0");
					put(grammarAccess.getGridsterAccess().getGroup(), "rule__Gridster__Group__0");
					put(grammarAccess.getGridsterAccess().getGroup_1(), "rule__Gridster__Group_1__0");
					put(grammarAccess.getGridsterAccess().getGroup_6(), "rule__Gridster__Group_6__0");
					put(grammarAccess.getGridsterAccess().getGroup_7(), "rule__Gridster__Group_7__0");
					put(grammarAccess.getGridsterAccess().getGroup_8(), "rule__Gridster__Group_8__0");
					put(grammarAccess.getGridsterAccess().getGroup_9(), "rule__Gridster__Group_9__0");
					put(grammarAccess.getClockAccess().getGroup(), "rule__Clock__Group__0");
					put(grammarAccess.getClockAccess().getGroup_6(), "rule__Clock__Group_6__0");
					put(grammarAccess.getClockAccess().getGroup_7(), "rule__Clock__Group_7__0");
					put(grammarAccess.getClockAccess().getGroup_8(), "rule__Clock__Group_8__0");
					put(grammarAccess.getClockAccess().getGroup_9(), "rule__Clock__Group_9__0");
					put(grammarAccess.getClockAccess().getGroup_10(), "rule__Clock__Group_10__0");
					put(grammarAccess.getClockAccess().getGroup_11(), "rule__Clock__Group_11__0");
					put(grammarAccess.getSwiperAccess().getGroup(), "rule__Swiper__Group__0");
					put(grammarAccess.getSwiperAccess().getGroup_6(), "rule__Swiper__Group_6__0");
					put(grammarAccess.getSwiperAccess().getGroup_7(), "rule__Swiper__Group_7__0");
					put(grammarAccess.getTemplateRefAccess().getGroup(), "rule__TemplateRef__Group__0");
					put(grammarAccess.getSelectAccess().getGroup(), "rule__Select__Group__0");
					put(grammarAccess.getSelectAccess().getGroup_3(), "rule__Select__Group_3__0");
					put(grammarAccess.getSelectAccess().getGroup_4(), "rule__Select__Group_4__0");
					put(grammarAccess.getSelectAccess().getGroup_5(), "rule__Select__Group_5__0");
					put(grammarAccess.getSelectAccess().getGroup_6(), "rule__Select__Group_6__0");
					put(grammarAccess.getSelectAccess().getGroup_7(), "rule__Select__Group_7__0");
					put(grammarAccess.getSelectAccess().getGroup_8(), "rule__Select__Group_8__0");
					put(grammarAccess.getSelectAccess().getGroup_9(), "rule__Select__Group_9__0");
					put(grammarAccess.getSelectAccess().getGroup_10(), "rule__Select__Group_10__0");
					put(grammarAccess.getVolumeAccess().getGroup(), "rule__Volume__Group__0");
					put(grammarAccess.getVolumeAccess().getGroup_3(), "rule__Volume__Group_3__0");
					put(grammarAccess.getVolumeAccess().getGroup_6(), "rule__Volume__Group_6__0");
					put(grammarAccess.getVolumeAccess().getGroup_7(), "rule__Volume__Group_7__0");
					put(grammarAccess.getVolumeAccess().getGroup_8(), "rule__Volume__Group_8__0");
					put(grammarAccess.getVolumeAccess().getGroup_9(), "rule__Volume__Group_9__0");
					put(grammarAccess.getPushAccess().getGroup(), "rule__Push__Group__0");
					put(grammarAccess.getPushAccess().getGroup_3(), "rule__Push__Group_3__0");
					put(grammarAccess.getPushAccess().getGroup_4(), "rule__Push__Group_4__0");
					put(grammarAccess.getPushAccess().getGroup_7(), "rule__Push__Group_7__0");
					put(grammarAccess.getPushAccess().getGroup_8(), "rule__Push__Group_8__0");
					put(grammarAccess.getPushAccess().getGroup_9(), "rule__Push__Group_9__0");
					put(grammarAccess.getPushAccess().getGroup_10(), "rule__Push__Group_10__0");
					put(grammarAccess.getPushAccess().getGroup_11(), "rule__Push__Group_11__0");
					put(grammarAccess.getPushAccess().getGroup_12(), "rule__Push__Group_12__0");
					put(grammarAccess.getImageAccess().getGroup(), "rule__Image__Group__0");
					put(grammarAccess.getImageAccess().getGroup_6(), "rule__Image__Group_6__0");
					put(grammarAccess.getSwitchAccess().getGroup(), "rule__Switch__Group__0");
					put(grammarAccess.getSwitchAccess().getGroup_3(), "rule__Switch__Group_3__0");
					put(grammarAccess.getSwitchAccess().getGroup_4(), "rule__Switch__Group_4__0");
					put(grammarAccess.getSwitchAccess().getGroup_5(), "rule__Switch__Group_5__0");
					put(grammarAccess.getSwitchAccess().getGroup_6(), "rule__Switch__Group_6__0");
					put(grammarAccess.getSwitchAccess().getGroup_7(), "rule__Switch__Group_7__0");
					put(grammarAccess.getSwitchAccess().getGroup_8(), "rule__Switch__Group_8__0");
					put(grammarAccess.getSwitchAccess().getGroup_9(), "rule__Switch__Group_9__0");
					put(grammarAccess.getSwitchAccess().getGroup_10(), "rule__Switch__Group_10__0");
					put(grammarAccess.getSwitchAccess().getGroup_11(), "rule__Switch__Group_11__0");
					put(grammarAccess.getSwitchAccess().getGroup_12(), "rule__Switch__Group_12__0");
					put(grammarAccess.getCustomAccess().getGroup(), "rule__Custom__Group__0");
					put(grammarAccess.getDivAccess().getGroup(), "rule__Div__Group__0");
					put(grammarAccess.getDivAccess().getGroup_2(), "rule__Div__Group_2__0");
					put(grammarAccess.getDivAccess().getGroup_3(), "rule__Div__Group_3__0");
					put(grammarAccess.getItunes_artworkAccess().getGroup(), "rule__Itunes_artwork__Group__0");
					put(grammarAccess.getItunes_artworkAccess().getGroup_5(), "rule__Itunes_artwork__Group_5__0");
					put(grammarAccess.getItunes_artworkAccess().getGroup_6(), "rule__Itunes_artwork__Group_6__0");
					put(grammarAccess.getItunes_artworkAccess().getGroup_7(), "rule__Itunes_artwork__Group_7__0");
					put(grammarAccess.getItunes_artworkAccess().getGroup_8(), "rule__Itunes_artwork__Group_8__0");
					put(grammarAccess.getWeatherAccess().getGroup(), "rule__Weather__Group__0");
					put(grammarAccess.getWeatherAccess().getGroup_3(), "rule__Weather__Group_3__0");
					put(grammarAccess.getWeatherAccess().getGroup_4(), "rule__Weather__Group_4__0");
					put(grammarAccess.getWeatherAccess().getGroup_5(), "rule__Weather__Group_5__0");
					put(grammarAccess.getWeatherAccess().getGroup_6(), "rule__Weather__Group_6__0");
					put(grammarAccess.getCalviewAccess().getGroup(), "rule__Calview__Group__0");
					put(grammarAccess.getCalviewAccess().getGroup_9(), "rule__Calview__Group_9__0");
					put(grammarAccess.getCalviewAccess().getGroup_10(), "rule__Calview__Group_10__0");
					put(grammarAccess.getPopupAccess().getGroup(), "rule__Popup__Group__0");
					put(grammarAccess.getPopupAccess().getGroup_2(), "rule__Popup__Group_2__0");
					put(grammarAccess.getPopupAccess().getGroup_3(), "rule__Popup__Group_3__0");
					put(grammarAccess.getPopupAccess().getGroup_6(), "rule__Popup__Group_6__0");
					put(grammarAccess.getPopupAccess().getGroup_7(), "rule__Popup__Group_7__0");
					put(grammarAccess.getPopupAccess().getGroup_8(), "rule__Popup__Group_8__0");
					put(grammarAccess.getPopupAccess().getGroup_9(), "rule__Popup__Group_9__0");
					put(grammarAccess.getPopupAccess().getGroup_10(), "rule__Popup__Group_10__0");
					put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
					put(grammarAccess.getLinkAccess().getGroup_2(), "rule__Link__Group_2__0");
					put(grammarAccess.getLinkAccess().getGroup_3(), "rule__Link__Group_3__0");
					put(grammarAccess.getLinkAccess().getGroup_4(), "rule__Link__Group_4__0");
					put(grammarAccess.getLinkAccess().getGroup_5(), "rule__Link__Group_5__0");
					put(grammarAccess.getLinkAccess().getGroup_6(), "rule__Link__Group_6__0");
					put(grammarAccess.getButtonUrlAccess().getGroup_0(), "rule__ButtonUrl__Group_0__0");
					put(grammarAccess.getButtonUrlAccess().getGroup_1(), "rule__ButtonUrl__Group_1__0");
					put(grammarAccess.getButtonUrlAccess().getGroup_2(), "rule__ButtonUrl__Group_2__0");
					put(grammarAccess.getButtonAccess().getGroup(), "rule__Button__Group__0");
					put(grammarAccess.getButtonAccess().getGroup_3(), "rule__Button__Group_3__0");
					put(grammarAccess.getButtonAccess().getGroup_4(), "rule__Button__Group_4__0");
					put(grammarAccess.getButtonAccess().getGroup_5(), "rule__Button__Group_5__0");
					put(grammarAccess.getButtonAccess().getGroup_6(), "rule__Button__Group_6__0");
					put(grammarAccess.getButtonAccess().getGroup_10(), "rule__Button__Group_10__0");
					put(grammarAccess.getButtonAccess().getGroup_13(), "rule__Button__Group_13__0");
					put(grammarAccess.getButtonAccess().getGroup_14(), "rule__Button__Group_14__0");
					put(grammarAccess.getButtonAccess().getGroup_15(), "rule__Button__Group_15__0");
					put(grammarAccess.getButtonAccess().getGroup_16(), "rule__Button__Group_16__0");
					put(grammarAccess.getKlimatrendAccess().getGroup(), "rule__Klimatrend__Group__0");
					put(grammarAccess.getKlimatrendAccess().getGroup_5(), "rule__Klimatrend__Group_5__0");
					put(grammarAccess.getKlimatrendAccess().getGroup_8(), "rule__Klimatrend__Group_8__0");
					put(grammarAccess.getKlimatrendAccess().getGroup_9(), "rule__Klimatrend__Group_9__0");
					put(grammarAccess.getKlimatrendAccess().getGroup_10(), "rule__Klimatrend__Group_10__0");
					put(grammarAccess.getKlimatrendAccess().getGroup_11(), "rule__Klimatrend__Group_11__0");
					put(grammarAccess.getKlimatrendAccess().getGroup_12(), "rule__Klimatrend__Group_12__0");
					put(grammarAccess.getKlimatrendAccess().getGroup_13(), "rule__Klimatrend__Group_13__0");
					put(grammarAccess.getKlimatrendAccess().getGroup_14(), "rule__Klimatrend__Group_14__0");
					put(grammarAccess.getKlimatrendAccess().getGroup_15(), "rule__Klimatrend__Group_15__0");
					put(grammarAccess.getSymbolAccess().getGroup(), "rule__Symbol__Group__0");
					put(grammarAccess.getSymbolAccess().getGroup_7(), "rule__Symbol__Group_7__0");
					put(grammarAccess.getSymbolAccess().getGroup_8(), "rule__Symbol__Group_8__0");
					put(grammarAccess.getSymbolAccess().getGroup_9(), "rule__Symbol__Group_9__0");
					put(grammarAccess.getSymbolAccess().getGroup_10(), "rule__Symbol__Group_10__0");
					put(grammarAccess.getSymbolAccess().getGroup_11(), "rule__Symbol__Group_11__0");
					put(grammarAccess.getSymbolAccess().getGroup_12(), "rule__Symbol__Group_12__0");
					put(grammarAccess.getSymbolAccess().getGroup_13(), "rule__Symbol__Group_13__0");
					put(grammarAccess.getSymbolAccess().getGroup_14(), "rule__Symbol__Group_14__0");
					put(grammarAccess.getSimpleClockAccess().getGroup(), "rule__SimpleClock__Group__0");
					put(grammarAccess.getSimpleClockAccess().getGroup_7(), "rule__SimpleClock__Group_7__0");
					put(grammarAccess.getSimpleClockAccess().getGroup_8(), "rule__SimpleClock__Group_8__0");
					put(grammarAccess.getSimpleClockAccess().getGroup_9(), "rule__SimpleClock__Group_9__0");
					put(grammarAccess.getSimpleClockAccess().getGroup_10(), "rule__SimpleClock__Group_10__0");
					put(grammarAccess.getSimpleClockAccess().getGroup_11(), "rule__SimpleClock__Group_11__0");
					put(grammarAccess.getSimpleChartAccess().getGroup(), "rule__SimpleChart__Group__0");
					put(grammarAccess.getColorAccess().getGroup(), "rule__Color__Group__0");
					put(grammarAccess.getLabelAccess().getGroup(), "rule__Label__Group__0");
					put(grammarAccess.getLabelAccess().getGroup_5(), "rule__Label__Group_5__0");
					put(grammarAccess.getLabelAccess().getGroup_6(), "rule__Label__Group_6__0");
					put(grammarAccess.getLabelAccess().getGroup_7(), "rule__Label__Group_7__0");
					put(grammarAccess.getLabelAccess().getGroup_8(), "rule__Label__Group_8__0");
					put(grammarAccess.getLabelAccess().getGroup_9(), "rule__Label__Group_9__0");
					put(grammarAccess.getTabletUIAccess().getSettingsAssignment_0(), "rule__TabletUI__SettingsAssignment_0");
					put(grammarAccess.getTabletUIAccess().getElementsAssignment_1(), "rule__TabletUI__ElementsAssignment_1");
					put(grammarAccess.getSettingsAccess().getTitleAssignment_2(), "rule__Settings__TitleAssignment_2");
					put(grammarAccess.getSettingsAccess().getFhemweb_urlAssignment_3_1(), "rule__Settings__Fhemweb_urlAssignment_3_1");
					put(grammarAccess.getSettingsAccess().getWidthAssignment_5(), "rule__Settings__WidthAssignment_5");
					put(grammarAccess.getSettingsAccess().getHeightAssignment_7(), "rule__Settings__HeightAssignment_7");
					put(grammarAccess.getSettingsAccess().getColumnsAssignment_9(), "rule__Settings__ColumnsAssignment_9");
					put(grammarAccess.getSettingsAccess().getRowsAssignment_11(), "rule__Settings__RowsAssignment_11");
					put(grammarAccess.getSettingsAccess().getDebugAssignment_12_1(), "rule__Settings__DebugAssignment_12_1");
					put(grammarAccess.getSettingsAccess().getDragdropAssignment_14(), "rule__Settings__DragdropAssignment_14");
					put(grammarAccess.getSettingsAccess().getMarginAssignment_16(), "rule__Settings__MarginAssignment_16");
					put(grammarAccess.getSettingsAccess().getSettingsAssignment_17(), "rule__Settings__SettingsAssignment_17");
					put(grammarAccess.getCSSAccess().getPathAssignment_1(), "rule__CSS__PathAssignment_1");
					put(grammarAccess.getPageAccess().getNameAssignment_0(), "rule__Page__NameAssignment_0");
					put(grammarAccess.getPageAccess().getScreensaverAssignment_2_1(), "rule__Page__ScreensaverAssignment_2_1");
					put(grammarAccess.getPageAccess().getElementsAssignment_3(), "rule__Page__ElementsAssignment_3");
					put(grammarAccess.getScreensaverAccess().getNameAssignment_2(), "rule__Screensaver__NameAssignment_2");
					put(grammarAccess.getScreensaverAccess().getWidgetsAssignment_3(), "rule__Screensaver__WidgetsAssignment_3");
					put(grammarAccess.getTemplateAccess().getNameAssignment_0(), "rule__Template__NameAssignment_0");
					put(grammarAccess.getTemplateAccess().getElementsAssignment_3(), "rule__Template__ElementsAssignment_3");
					put(grammarAccess.getGridsterAccess().getHeaderAssignment_1_1(), "rule__Gridster__HeaderAssignment_1_1");
					put(grammarAccess.getGridsterAccess().getRowAssignment_3(), "rule__Gridster__RowAssignment_3");
					put(grammarAccess.getGridsterAccess().getColumnAssignment_5(), "rule__Gridster__ColumnAssignment_5");
					put(grammarAccess.getGridsterAccess().getColspanAssignment_6_1(), "rule__Gridster__ColspanAssignment_6_1");
					put(grammarAccess.getGridsterAccess().getRowspanAssignment_7_1(), "rule__Gridster__RowspanAssignment_7_1");
					put(grammarAccess.getGridsterAccess().getClassAssignment_8_1(), "rule__Gridster__ClassAssignment_8_1");
					put(grammarAccess.getGridsterAccess().getStyleAssignment_9_1(), "rule__Gridster__StyleAssignment_9_1");
					put(grammarAccess.getGridsterAccess().getColorsAssignment_10(), "rule__Gridster__ColorsAssignment_10");
					put(grammarAccess.getGridsterAccess().getWidgetsAssignment_11(), "rule__Gridster__WidgetsAssignment_11");
					put(grammarAccess.getClockAccess().getFormatAssignment_3(), "rule__Clock__FormatAssignment_3");
					put(grammarAccess.getClockAccess().getClassAssignment_5(), "rule__Clock__ClassAssignment_5");
					put(grammarAccess.getClockAccess().getStyleAssignment_6_1(), "rule__Clock__StyleAssignment_6_1");
					put(grammarAccess.getClockAccess().getIntervalAssignment_7_1(), "rule__Clock__IntervalAssignment_7_1");
					put(grammarAccess.getClockAccess().getDaysAssignment_8_1(), "rule__Clock__DaysAssignment_8_1");
					put(grammarAccess.getClockAccess().getShortdayLengthAssignment_9_1(), "rule__Clock__ShortdayLengthAssignment_9_1");
					put(grammarAccess.getClockAccess().getMonthAssignment_10_1(), "rule__Clock__MonthAssignment_10_1");
					put(grammarAccess.getClockAccess().getMonthLengthAssignment_11_1(), "rule__Clock__MonthLengthAssignment_11_1");
					put(grammarAccess.getSwiperAccess().getWidthAssignment_3(), "rule__Swiper__WidthAssignment_3");
					put(grammarAccess.getSwiperAccess().getHeightAssignment_5(), "rule__Swiper__HeightAssignment_5");
					put(grammarAccess.getSwiperAccess().getAutoplayAssignment_6_1(), "rule__Swiper__AutoplayAssignment_6_1");
					put(grammarAccess.getSwiperAccess().getClassAssignment_7_1(), "rule__Swiper__ClassAssignment_7_1");
					put(grammarAccess.getSwiperAccess().getDivsAssignment_8(), "rule__Swiper__DivsAssignment_8");
					put(grammarAccess.getTemplateRefAccess().getTemplateAssignment_1(), "rule__TemplateRef__TemplateAssignment_1");
					put(grammarAccess.getSelectAccess().getDeviceAssignment_2(), "rule__Select__DeviceAssignment_2");
					put(grammarAccess.getSelectAccess().getListAssignment_3_1(), "rule__Select__ListAssignment_3_1");
					put(grammarAccess.getSelectAccess().getItemsAssignment_4_1(), "rule__Select__ItemsAssignment_4_1");
					put(grammarAccess.getSelectAccess().getAliasAssignment_5_1(), "rule__Select__AliasAssignment_5_1");
					put(grammarAccess.getSelectAccess().getCmdAssignment_6_1(), "rule__Select__CmdAssignment_6_1");
					put(grammarAccess.getSelectAccess().getQuoteAssignment_7_1(), "rule__Select__QuoteAssignment_7_1");
					put(grammarAccess.getSelectAccess().getGetAssignment_8_1(), "rule__Select__GetAssignment_8_1");
					put(grammarAccess.getSelectAccess().getSetAssignment_9_1(), "rule__Select__SetAssignment_9_1");
					put(grammarAccess.getSelectAccess().getClassAssignment_10_1(), "rule__Select__ClassAssignment_10_1");
					put(grammarAccess.getVolumeAccess().getDeviceAssignment_2(), "rule__Volume__DeviceAssignment_2");
					put(grammarAccess.getVolumeAccess().getGetAssignment_3_1(), "rule__Volume__GetAssignment_3_1");
					put(grammarAccess.getVolumeAccess().getSetAssignment_5(), "rule__Volume__SetAssignment_5");
					put(grammarAccess.getVolumeAccess().getCmdAssignment_6_1(), "rule__Volume__CmdAssignment_6_1");
					put(grammarAccess.getVolumeAccess().getMinAssignment_7_1(), "rule__Volume__MinAssignment_7_1");
					put(grammarAccess.getVolumeAccess().getMaxAssignment_8_1(), "rule__Volume__MaxAssignment_8_1");
					put(grammarAccess.getVolumeAccess().getClassAssignment_9_1(), "rule__Volume__ClassAssignment_9_1");
					put(grammarAccess.getPushAccess().getDeviceAssignment_2(), "rule__Push__DeviceAssignment_2");
					put(grammarAccess.getPushAccess().getDataSetAssignment_3_1(), "rule__Push__DataSetAssignment_3_1");
					put(grammarAccess.getPushAccess().getSetOnAssignment_4_1(), "rule__Push__SetOnAssignment_4_1");
					put(grammarAccess.getPushAccess().getIconAssignment_6(), "rule__Push__IconAssignment_6");
					put(grammarAccess.getPushAccess().getBackgroundIconAssignment_7_1(), "rule__Push__BackgroundIconAssignment_7_1");
					put(grammarAccess.getPushAccess().getCmdAssignment_8_1(), "rule__Push__CmdAssignment_8_1");
					put(grammarAccess.getPushAccess().getDoubleClickAssignment_9_1(), "rule__Push__DoubleClickAssignment_9_1");
					put(grammarAccess.getPushAccess().getCountdownAssignment_10_1(), "rule__Push__CountdownAssignment_10_1");
					put(grammarAccess.getPushAccess().getClassAssignment_11_1(), "rule__Push__ClassAssignment_11_1");
					put(grammarAccess.getPushAccess().getUrlAssignment_12_1(), "rule__Push__UrlAssignment_12_1");
					put(grammarAccess.getImageAccess().getDeviceAssignment_1(), "rule__Image__DeviceAssignment_1");
					put(grammarAccess.getImageAccess().getGetAssignment_3(), "rule__Image__GetAssignment_3");
					put(grammarAccess.getImageAccess().getSizeAssignment_5(), "rule__Image__SizeAssignment_5");
					put(grammarAccess.getImageAccess().getClassAssignment_6_1(), "rule__Image__ClassAssignment_6_1");
					put(grammarAccess.getSwitchAccess().getDeviceAssignment_2(), "rule__Switch__DeviceAssignment_2");
					put(grammarAccess.getSwitchAccess().getGetAssignment_3_1(), "rule__Switch__GetAssignment_3_1");
					put(grammarAccess.getSwitchAccess().getGetOnAssignment_4_1(), "rule__Switch__GetOnAssignment_4_1");
					put(grammarAccess.getSwitchAccess().getSetOnAssignment_5_1(), "rule__Switch__SetOnAssignment_5_1");
					put(grammarAccess.getSwitchAccess().getGetOffAssignment_6_1(), "rule__Switch__GetOffAssignment_6_1");
					put(grammarAccess.getSwitchAccess().getClassAssignment_7_1(), "rule__Switch__ClassAssignment_7_1");
					put(grammarAccess.getSwitchAccess().getOnColorAssignment_8_1(), "rule__Switch__OnColorAssignment_8_1");
					put(grammarAccess.getSwitchAccess().getOffColorAssignment_9_1(), "rule__Switch__OffColorAssignment_9_1");
					put(grammarAccess.getSwitchAccess().getOnBackGroundColorAssignment_10_1(), "rule__Switch__OnBackGroundColorAssignment_10_1");
					put(grammarAccess.getSwitchAccess().getBackgroundIconAssignment_11_1(), "rule__Switch__BackgroundIconAssignment_11_1");
					put(grammarAccess.getSwitchAccess().getIconAssignment_12_1(), "rule__Switch__IconAssignment_12_1");
					put(grammarAccess.getCustomAccess().getCodeAssignment_2(), "rule__Custom__CodeAssignment_2");
					put(grammarAccess.getDivAccess().getClassAssignment_2_1(), "rule__Div__ClassAssignment_2_1");
					put(grammarAccess.getDivAccess().getStyleAssignment_3_1(), "rule__Div__StyleAssignment_3_1");
					put(grammarAccess.getDivAccess().getWidgetsAssignment_4(), "rule__Div__WidgetsAssignment_4");
					put(grammarAccess.getItunes_artworkAccess().getDeviceAssignment_2(), "rule__Itunes_artwork__DeviceAssignment_2");
					put(grammarAccess.getItunes_artworkAccess().getGetAssignment_4(), "rule__Itunes_artwork__GetAssignment_4");
					put(grammarAccess.getItunes_artworkAccess().getOpacityAssignment_5_1(), "rule__Itunes_artwork__OpacityAssignment_5_1");
					put(grammarAccess.getItunes_artworkAccess().getSizeAssignment_6_1(), "rule__Itunes_artwork__SizeAssignment_6_1");
					put(grammarAccess.getItunes_artworkAccess().getClassAssignment_7_1(), "rule__Itunes_artwork__ClassAssignment_7_1");
					put(grammarAccess.getItunes_artworkAccess().getStyleAssignment_8_1(), "rule__Itunes_artwork__StyleAssignment_8_1");
					put(grammarAccess.getWeatherAccess().getDeviceAssignment_2(), "rule__Weather__DeviceAssignment_2");
					put(grammarAccess.getWeatherAccess().getGetAssignment_3_1(), "rule__Weather__GetAssignment_3_1");
					put(grammarAccess.getWeatherAccess().getClassAssignment_4_1(), "rule__Weather__ClassAssignment_4_1");
					put(grammarAccess.getWeatherAccess().getImagesetAssignment_5_1(), "rule__Weather__ImagesetAssignment_5_1");
					put(grammarAccess.getWeatherAccess().getImagePathAssignment_6_1(), "rule__Weather__ImagePathAssignment_6_1");
					put(grammarAccess.getCalviewAccess().getDeviceAssignment_2(), "rule__Calview__DeviceAssignment_2");
					put(grammarAccess.getCalviewAccess().getGetAssignment_4(), "rule__Calview__GetAssignment_4");
					put(grammarAccess.getCalviewAccess().getMaxAssignment_6(), "rule__Calview__MaxAssignment_6");
					put(grammarAccess.getCalviewAccess().getClassAssignment_8(), "rule__Calview__ClassAssignment_8");
					put(grammarAccess.getCalviewAccess().getAllFCAssignment_9_1(), "rule__Calview__AllFCAssignment_9_1");
					put(grammarAccess.getCalviewAccess().getAllTCAssignment_10_1(), "rule__Calview__AllTCAssignment_10_1");
					put(grammarAccess.getPopupAccess().getWidthAssignment_2_1(), "rule__Popup__WidthAssignment_2_1");
					put(grammarAccess.getPopupAccess().getHeightAssignment_3_1(), "rule__Popup__HeightAssignment_3_1");
					put(grammarAccess.getPopupAccess().getOpenIconAssignment_5(), "rule__Popup__OpenIconAssignment_5");
					put(grammarAccess.getPopupAccess().getOpenBackgroundIconAssignment_6_1(), "rule__Popup__OpenBackgroundIconAssignment_6_1");
					put(grammarAccess.getPopupAccess().getOpenClassAssignment_7_1(), "rule__Popup__OpenClassAssignment_7_1");
					put(grammarAccess.getPopupAccess().getDialogClassAssignment_8_1(), "rule__Popup__DialogClassAssignment_8_1");
					put(grammarAccess.getPopupAccess().getDialogHeaderClassAssignment_9_1(), "rule__Popup__DialogHeaderClassAssignment_9_1");
					put(grammarAccess.getPopupAccess().getHeaderAssignment_10_1(), "rule__Popup__HeaderAssignment_10_1");
					put(grammarAccess.getPopupAccess().getWidgetsAssignment_11(), "rule__Popup__WidgetsAssignment_11");
					put(grammarAccess.getLinkAccess().getWidthAssignment_2_1(), "rule__Link__WidthAssignment_2_1");
					put(grammarAccess.getLinkAccess().getHeightAssignment_3_1(), "rule__Link__HeightAssignment_3_1");
					put(grammarAccess.getLinkAccess().getColorAssignment_4_1(), "rule__Link__ColorAssignment_4_1");
					put(grammarAccess.getLinkAccess().getClassAssignment_5_1(), "rule__Link__ClassAssignment_5_1");
					put(grammarAccess.getLinkAccess().getBackgroundColorAssignment_6_1(), "rule__Link__BackgroundColorAssignment_6_1");
					put(grammarAccess.getLinkAccess().getIconAssignment_8(), "rule__Link__IconAssignment_8");
					put(grammarAccess.getLinkAccess().getCmdAssignment_10(), "rule__Link__CmdAssignment_10");
					put(grammarAccess.getLinkAccess().getLabelAssignment_12(), "rule__Link__LabelAssignment_12");
					put(grammarAccess.getButtonUrlAccess().getUrlAssignment_0_1(), "rule__ButtonUrl__UrlAssignment_0_1");
					put(grammarAccess.getButtonUrlAccess().getPageAssignment_1_1(), "rule__ButtonUrl__PageAssignment_1_1");
					put(grammarAccess.getButtonUrlAccess().getFhemCmdAssignment_2_1(), "rule__ButtonUrl__FhemCmdAssignment_2_1");
					put(grammarAccess.getButtonAccess().getDeviceAssignment_2(), "rule__Button__DeviceAssignment_2");
					put(grammarAccess.getButtonAccess().getGetAssignment_3_1(), "rule__Button__GetAssignment_3_1");
					put(grammarAccess.getButtonAccess().getGetOnAssignment_4_1(), "rule__Button__GetOnAssignment_4_1");
					put(grammarAccess.getButtonAccess().getGetWarnAssignment_5_1(), "rule__Button__GetWarnAssignment_5_1");
					put(grammarAccess.getButtonAccess().getGetOffAssignment_6_1(), "rule__Button__GetOffAssignment_6_1");
					put(grammarAccess.getButtonAccess().getTargetAssignment_7(), "rule__Button__TargetAssignment_7");
					put(grammarAccess.getButtonAccess().getIconAssignment_9(), "rule__Button__IconAssignment_9");
					put(grammarAccess.getButtonAccess().getBackgroundIconAssignment_10_1(), "rule__Button__BackgroundIconAssignment_10_1");
					put(grammarAccess.getButtonAccess().getClassAssignment_12(), "rule__Button__ClassAssignment_12");
					put(grammarAccess.getButtonAccess().getOnColorAssignment_13_1(), "rule__Button__OnColorAssignment_13_1");
					put(grammarAccess.getButtonAccess().getOnBackgroundColorAssignment_14_1(), "rule__Button__OnBackgroundColorAssignment_14_1");
					put(grammarAccess.getButtonAccess().getOffColorAssignment_15_1(), "rule__Button__OffColorAssignment_15_1");
					put(grammarAccess.getButtonAccess().getOffBackgroundColorAssignment_16_1(), "rule__Button__OffBackgroundColorAssignment_16_1");
					put(grammarAccess.getKlimatrendAccess().getDeviceAssignment_2(), "rule__Klimatrend__DeviceAssignment_2");
					put(grammarAccess.getKlimatrendAccess().getGetAssignment_4(), "rule__Klimatrend__GetAssignment_4");
					put(grammarAccess.getKlimatrendAccess().getClassAssignment_5_1(), "rule__Klimatrend__ClassAssignment_5_1");
					put(grammarAccess.getKlimatrendAccess().getRefperiodAssignment_7(), "rule__Klimatrend__RefperiodAssignment_7");
					put(grammarAccess.getKlimatrendAccess().getStagnatingColorAssignment_8_1(), "rule__Klimatrend__StagnatingColorAssignment_8_1");
					put(grammarAccess.getKlimatrendAccess().getIconAssignment_9_1(), "rule__Klimatrend__IconAssignment_9_1");
					put(grammarAccess.getKlimatrendAccess().getRisingColorAssignment_10_1(), "rule__Klimatrend__RisingColorAssignment_10_1");
					put(grammarAccess.getKlimatrendAccess().getFallingColorAssignment_11_1(), "rule__Klimatrend__FallingColorAssignment_11_1");
					put(grammarAccess.getKlimatrendAccess().getHighmarkAssignment_12_1(), "rule__Klimatrend__HighmarkAssignment_12_1");
					put(grammarAccess.getKlimatrendAccess().getHighmarkIconAssignment_13_1(), "rule__Klimatrend__HighmarkIconAssignment_13_1");
					put(grammarAccess.getKlimatrendAccess().getHighmarkRisingColorAssignment_14_1(), "rule__Klimatrend__HighmarkRisingColorAssignment_14_1");
					put(grammarAccess.getKlimatrendAccess().getHighmarkFallingColorAssignment_15_1(), "rule__Klimatrend__HighmarkFallingColorAssignment_15_1");
					put(grammarAccess.getSymbolAccess().getDeviceAssignment_2(), "rule__Symbol__DeviceAssignment_2");
					put(grammarAccess.getSymbolAccess().getGetAssignment_4(), "rule__Symbol__GetAssignment_4");
					put(grammarAccess.getSymbolAccess().getGetOnAssignment_6(), "rule__Symbol__GetOnAssignment_6");
					put(grammarAccess.getSymbolAccess().getGetWarnAssignment_7_1(), "rule__Symbol__GetWarnAssignment_7_1");
					put(grammarAccess.getSymbolAccess().getGetOffAssignment_8_1(), "rule__Symbol__GetOffAssignment_8_1");
					put(grammarAccess.getSymbolAccess().getClassAssignment_9_1(), "rule__Symbol__ClassAssignment_9_1");
					put(grammarAccess.getSymbolAccess().getBgiconAssignment_10_1(), "rule__Symbol__BgiconAssignment_10_1");
					put(grammarAccess.getSymbolAccess().getOffColorAssignment_11_1(), "rule__Symbol__OffColorAssignment_11_1");
					put(grammarAccess.getSymbolAccess().getIconsAssignment_12_1(), "rule__Symbol__IconsAssignment_12_1");
					put(grammarAccess.getSymbolAccess().getOnColorsAssignment_13_1(), "rule__Symbol__OnColorsAssignment_13_1");
					put(grammarAccess.getSymbolAccess().getOnBackgroundColorsAssignment_14_1(), "rule__Symbol__OnBackgroundColorsAssignment_14_1");
					put(grammarAccess.getSimpleClockAccess().getIdAssignment_2(), "rule__SimpleClock__IdAssignment_2");
					put(grammarAccess.getSimpleClockAccess().getDateFormatAssignment_4(), "rule__SimpleClock__DateFormatAssignment_4");
					put(grammarAccess.getSimpleClockAccess().getTimeFormatAssignment_6(), "rule__SimpleClock__TimeFormatAssignment_6");
					put(grammarAccess.getSimpleClockAccess().getDateColorAssignment_7_1(), "rule__SimpleClock__DateColorAssignment_7_1");
					put(grammarAccess.getSimpleClockAccess().getTimeColorAssignment_8_1(), "rule__SimpleClock__TimeColorAssignment_8_1");
					put(grammarAccess.getSimpleClockAccess().getClassAssignment_9_1(), "rule__SimpleClock__ClassAssignment_9_1");
					put(grammarAccess.getSimpleClockAccess().getStyleAssignment_10_1(), "rule__SimpleClock__StyleAssignment_10_1");
					put(grammarAccess.getSimpleClockAccess().getBgColorsAssignment_11_1(), "rule__SimpleClock__BgColorsAssignment_11_1");
					put(grammarAccess.getSimpleChartAccess().getDeviceAssignment_2(), "rule__SimpleChart__DeviceAssignment_2");
					put(grammarAccess.getSimpleChartAccess().getLog_deviceAssignment_4(), "rule__SimpleChart__Log_deviceAssignment_4");
					put(grammarAccess.getSimpleChartAccess().getLogfileAssignment_5(), "rule__SimpleChart__LogfileAssignment_5");
					put(grammarAccess.getSimpleChartAccess().getColumnSpecAssignment_7(), "rule__SimpleChart__ColumnSpecAssignment_7");
					put(grammarAccess.getSimpleChartAccess().getMinAssignment_9(), "rule__SimpleChart__MinAssignment_9");
					put(grammarAccess.getSimpleChartAccess().getMaxAssignment_11(), "rule__SimpleChart__MaxAssignment_11");
					put(grammarAccess.getSimpleChartAccess().getXTicksAssignment_13(), "rule__SimpleChart__XTicksAssignment_13");
					put(grammarAccess.getSimpleChartAccess().getYTicksAssignment_15(), "rule__SimpleChart__YTicksAssignment_15");
					put(grammarAccess.getSimpleChartAccess().getDaysagoAssignment_17(), "rule__SimpleChart__DaysagoAssignment_17");
					put(grammarAccess.getSimpleChartAccess().getClassAssignment_19(), "rule__SimpleChart__ClassAssignment_19");
					put(grammarAccess.getColorAccess().getNameAssignment_1(), "rule__Color__NameAssignment_1");
					put(grammarAccess.getColorAccess().getRgbAssignment_2(), "rule__Color__RgbAssignment_2");
					put(grammarAccess.getLabelAccess().getDeviceAssignment_2(), "rule__Label__DeviceAssignment_2");
					put(grammarAccess.getLabelAccess().getGetAssignment_4(), "rule__Label__GetAssignment_4");
					put(grammarAccess.getLabelAccess().getClassAssignment_5_1(), "rule__Label__ClassAssignment_5_1");
					put(grammarAccess.getLabelAccess().getStyleAssignment_6_1(), "rule__Label__StyleAssignment_6_1");
					put(grammarAccess.getLabelAccess().getUnitAssignment_7_1(), "rule__Label__UnitAssignment_7_1");
					put(grammarAccess.getLabelAccess().getPartAssignment_8_1(), "rule__Label__PartAssignment_8_1");
					put(grammarAccess.getLabelAccess().getSubstitutionAssignment_9_1(), "rule__Label__SubstitutionAssignment_9_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.ckr.ui.contentassist.antlr.internal.InternalTabletUIDSLParser typedParser = (org.ckr.ui.contentassist.antlr.internal.InternalTabletUIDSLParser) parser;
			typedParser.entryRuleTabletUI();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public TabletUIDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TabletUIDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
