/*
 * generated by Xtext
 */
package org.ckr.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.ckr.services.TabletUIDSLGrammarAccess;

public class TabletUIDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private TabletUIDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.ckr.ui.contentassist.antlr.internal.InternalTabletUIDSLParser createParser() {
		org.ckr.ui.contentassist.antlr.internal.InternalTabletUIDSLParser result = new org.ckr.ui.contentassist.antlr.internal.InternalTabletUIDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSettingsElementAccess().getAlternatives(), "rule__SettingsElement__Alternatives");
					put(grammarAccess.getBOOLAccess().getAlternatives(), "rule__BOOL__Alternatives");
					put(grammarAccess.getWidgetAccess().getAlternatives(), "rule__Widget__Alternatives");
					put(grammarAccess.getTabletUIAccess().getGroup(), "rule__TabletUI__Group__0");
					put(grammarAccess.getSettingsAccess().getGroup(), "rule__Settings__Group__0");
					put(grammarAccess.getSettingsAccess().getGroup_3(), "rule__Settings__Group_3__0");
					put(grammarAccess.getSettingsAccess().getGroup_12(), "rule__Settings__Group_12__0");
					put(grammarAccess.getCSSAccess().getGroup(), "rule__CSS__Group__0");
					put(grammarAccess.getPageAccess().getGroup(), "rule__Page__Group__0");
					put(grammarAccess.getGridsterAccess().getGroup(), "rule__Gridster__Group__0");
					put(grammarAccess.getGridsterAccess().getGroup_1(), "rule__Gridster__Group_1__0");
					put(grammarAccess.getGridsterAccess().getGroup_6(), "rule__Gridster__Group_6__0");
					put(grammarAccess.getGridsterAccess().getGroup_7(), "rule__Gridster__Group_7__0");
					put(grammarAccess.getDivAccess().getGroup(), "rule__Div__Group__0");
					put(grammarAccess.getCalviewAccess().getGroup(), "rule__Calview__Group__0");
					put(grammarAccess.getCalviewAccess().getGroup_9(), "rule__Calview__Group_9__0");
					put(grammarAccess.getCalviewAccess().getGroup_10(), "rule__Calview__Group_10__0");
					put(grammarAccess.getButtonAccess().getGroup(), "rule__Button__Group__0");
					put(grammarAccess.getButtonAccess().getGroup_3(), "rule__Button__Group_3__0");
					put(grammarAccess.getButtonAccess().getGroup_8(), "rule__Button__Group_8__0");
					put(grammarAccess.getButtonAccess().getGroup_9(), "rule__Button__Group_9__0");
					put(grammarAccess.getSymbolAccess().getGroup(), "rule__Symbol__Group__0");
					put(grammarAccess.getSymbolAccess().getGroup_7(), "rule__Symbol__Group_7__0");
					put(grammarAccess.getSymbolAccess().getGroup_8(), "rule__Symbol__Group_8__0");
					put(grammarAccess.getSymbolAccess().getGroup_9(), "rule__Symbol__Group_9__0");
					put(grammarAccess.getSymbolAccess().getGroup_10(), "rule__Symbol__Group_10__0");
					put(grammarAccess.getSymbolAccess().getGroup_11(), "rule__Symbol__Group_11__0");
					put(grammarAccess.getSymbolAccess().getGroup_12(), "rule__Symbol__Group_12__0");
					put(grammarAccess.getSymbolAccess().getGroup_13(), "rule__Symbol__Group_13__0");
					put(grammarAccess.getSymbolAccess().getGroup_14(), "rule__Symbol__Group_14__0");
					put(grammarAccess.getSymbolAccess().getGroup_15(), "rule__Symbol__Group_15__0");
					put(grammarAccess.getSimpleClockAccess().getGroup(), "rule__SimpleClock__Group__0");
					put(grammarAccess.getSimpleClockAccess().getGroup_7(), "rule__SimpleClock__Group_7__0");
					put(grammarAccess.getSimpleClockAccess().getGroup_8(), "rule__SimpleClock__Group_8__0");
					put(grammarAccess.getSimpleClockAccess().getGroup_9(), "rule__SimpleClock__Group_9__0");
					put(grammarAccess.getSimpleClockAccess().getGroup_10(), "rule__SimpleClock__Group_10__0");
					put(grammarAccess.getSimpleClockAccess().getGroup_11(), "rule__SimpleClock__Group_11__0");
					put(grammarAccess.getSimpleChartAccess().getGroup(), "rule__SimpleChart__Group__0");
					put(grammarAccess.getColorAccess().getGroup(), "rule__Color__Group__0");
					put(grammarAccess.getLabelAccess().getGroup(), "rule__Label__Group__0");
					put(grammarAccess.getTabletUIAccess().getSettingsAssignment_0(), "rule__TabletUI__SettingsAssignment_0");
					put(grammarAccess.getTabletUIAccess().getElementsAssignment_1(), "rule__TabletUI__ElementsAssignment_1");
					put(grammarAccess.getSettingsAccess().getTitleAssignment_2(), "rule__Settings__TitleAssignment_2");
					put(grammarAccess.getSettingsAccess().getFhemweb_urlAssignment_3_1(), "rule__Settings__Fhemweb_urlAssignment_3_1");
					put(grammarAccess.getSettingsAccess().getWidthAssignment_5(), "rule__Settings__WidthAssignment_5");
					put(grammarAccess.getSettingsAccess().getHeightAssignment_7(), "rule__Settings__HeightAssignment_7");
					put(grammarAccess.getSettingsAccess().getColumnsAssignment_9(), "rule__Settings__ColumnsAssignment_9");
					put(grammarAccess.getSettingsAccess().getRowsAssignment_11(), "rule__Settings__RowsAssignment_11");
					put(grammarAccess.getSettingsAccess().getDebugAssignment_12_1(), "rule__Settings__DebugAssignment_12_1");
					put(grammarAccess.getSettingsAccess().getDragdropAssignment_14(), "rule__Settings__DragdropAssignment_14");
					put(grammarAccess.getSettingsAccess().getMarginAssignment_16(), "rule__Settings__MarginAssignment_16");
					put(grammarAccess.getSettingsAccess().getSettingsAssignment_17(), "rule__Settings__SettingsAssignment_17");
					put(grammarAccess.getCSSAccess().getPathAssignment_1(), "rule__CSS__PathAssignment_1");
					put(grammarAccess.getPageAccess().getNameAssignment_0(), "rule__Page__NameAssignment_0");
					put(grammarAccess.getPageAccess().getElementsAssignment_2(), "rule__Page__ElementsAssignment_2");
					put(grammarAccess.getGridsterAccess().getHeaderAssignment_1_1(), "rule__Gridster__HeaderAssignment_1_1");
					put(grammarAccess.getGridsterAccess().getRowAssignment_3(), "rule__Gridster__RowAssignment_3");
					put(grammarAccess.getGridsterAccess().getColumnAssignment_5(), "rule__Gridster__ColumnAssignment_5");
					put(grammarAccess.getGridsterAccess().getColspanAssignment_6_1(), "rule__Gridster__ColspanAssignment_6_1");
					put(grammarAccess.getGridsterAccess().getRowspanAssignment_7_1(), "rule__Gridster__RowspanAssignment_7_1");
					put(grammarAccess.getGridsterAccess().getColorsAssignment_8(), "rule__Gridster__ColorsAssignment_8");
					put(grammarAccess.getGridsterAccess().getWidgetsAssignment_9(), "rule__Gridster__WidgetsAssignment_9");
					put(grammarAccess.getDivAccess().getClassAssignment_3(), "rule__Div__ClassAssignment_3");
					put(grammarAccess.getDivAccess().getWidgetsAssignment_4(), "rule__Div__WidgetsAssignment_4");
					put(grammarAccess.getCalviewAccess().getDeviceAssignment_2(), "rule__Calview__DeviceAssignment_2");
					put(grammarAccess.getCalviewAccess().getGetAssignment_4(), "rule__Calview__GetAssignment_4");
					put(grammarAccess.getCalviewAccess().getMaxAssignment_6(), "rule__Calview__MaxAssignment_6");
					put(grammarAccess.getCalviewAccess().getClassAssignment_8(), "rule__Calview__ClassAssignment_8");
					put(grammarAccess.getCalviewAccess().getAllFCAssignment_9_1(), "rule__Calview__AllFCAssignment_9_1");
					put(grammarAccess.getCalviewAccess().getAllTCAssignment_10_1(), "rule__Calview__AllTCAssignment_10_1");
					put(grammarAccess.getButtonAccess().getIdAssignment_2(), "rule__Button__IdAssignment_2");
					put(grammarAccess.getButtonAccess().getUrlAssignment_3_1(), "rule__Button__UrlAssignment_3_1");
					put(grammarAccess.getButtonAccess().getIconAssignment_5(), "rule__Button__IconAssignment_5");
					put(grammarAccess.getButtonAccess().getClassAssignment_7(), "rule__Button__ClassAssignment_7");
					put(grammarAccess.getButtonAccess().getColorAssignment_8_1(), "rule__Button__ColorAssignment_8_1");
					put(grammarAccess.getButtonAccess().getBackgroundColorAssignment_9_1(), "rule__Button__BackgroundColorAssignment_9_1");
					put(grammarAccess.getSymbolAccess().getDeviceAssignment_2(), "rule__Symbol__DeviceAssignment_2");
					put(grammarAccess.getSymbolAccess().getGetAssignment_4(), "rule__Symbol__GetAssignment_4");
					put(grammarAccess.getSymbolAccess().getGetOnAssignment_6(), "rule__Symbol__GetOnAssignment_6");
					put(grammarAccess.getSymbolAccess().getGetOffAssignment_7_1(), "rule__Symbol__GetOffAssignment_7_1");
					put(grammarAccess.getSymbolAccess().getClassAssignment_8_1(), "rule__Symbol__ClassAssignment_8_1");
					put(grammarAccess.getSymbolAccess().getBgiconAssignment_9_1(), "rule__Symbol__BgiconAssignment_9_1");
					put(grammarAccess.getSymbolAccess().getOnBackGroundColorAssignment_10_1(), "rule__Symbol__OnBackGroundColorAssignment_10_1");
					put(grammarAccess.getSymbolAccess().getOnColorAssignment_11_1(), "rule__Symbol__OnColorAssignment_11_1");
					put(grammarAccess.getSymbolAccess().getOffColorAssignment_12_1(), "rule__Symbol__OffColorAssignment_12_1");
					put(grammarAccess.getSymbolAccess().getIconsAssignment_13_2(), "rule__Symbol__IconsAssignment_13_2");
					put(grammarAccess.getSymbolAccess().getOnColorsAssignment_14_2(), "rule__Symbol__OnColorsAssignment_14_2");
					put(grammarAccess.getSymbolAccess().getOnBackgroundColorsAssignment_15_2(), "rule__Symbol__OnBackgroundColorsAssignment_15_2");
					put(grammarAccess.getSimpleClockAccess().getIdAssignment_2(), "rule__SimpleClock__IdAssignment_2");
					put(grammarAccess.getSimpleClockAccess().getDateFormatAssignment_4(), "rule__SimpleClock__DateFormatAssignment_4");
					put(grammarAccess.getSimpleClockAccess().getTimeFormatAssignment_6(), "rule__SimpleClock__TimeFormatAssignment_6");
					put(grammarAccess.getSimpleClockAccess().getDateColorAssignment_7_1(), "rule__SimpleClock__DateColorAssignment_7_1");
					put(grammarAccess.getSimpleClockAccess().getTimeColorAssignment_8_1(), "rule__SimpleClock__TimeColorAssignment_8_1");
					put(grammarAccess.getSimpleClockAccess().getClassAssignment_9_1(), "rule__SimpleClock__ClassAssignment_9_1");
					put(grammarAccess.getSimpleClockAccess().getStyleAssignment_10_1(), "rule__SimpleClock__StyleAssignment_10_1");
					put(grammarAccess.getSimpleClockAccess().getBgColorsAssignment_11_1(), "rule__SimpleClock__BgColorsAssignment_11_1");
					put(grammarAccess.getSimpleChartAccess().getDeviceAssignment_2(), "rule__SimpleChart__DeviceAssignment_2");
					put(grammarAccess.getSimpleChartAccess().getLog_deviceAssignment_4(), "rule__SimpleChart__Log_deviceAssignment_4");
					put(grammarAccess.getSimpleChartAccess().getLogfileAssignment_5(), "rule__SimpleChart__LogfileAssignment_5");
					put(grammarAccess.getSimpleChartAccess().getColumnSpecAssignment_7(), "rule__SimpleChart__ColumnSpecAssignment_7");
					put(grammarAccess.getSimpleChartAccess().getMinAssignment_9(), "rule__SimpleChart__MinAssignment_9");
					put(grammarAccess.getSimpleChartAccess().getMaxAssignment_11(), "rule__SimpleChart__MaxAssignment_11");
					put(grammarAccess.getSimpleChartAccess().getXTicksAssignment_13(), "rule__SimpleChart__XTicksAssignment_13");
					put(grammarAccess.getSimpleChartAccess().getYTicksAssignment_15(), "rule__SimpleChart__YTicksAssignment_15");
					put(grammarAccess.getSimpleChartAccess().getDaysagoAssignment_17(), "rule__SimpleChart__DaysagoAssignment_17");
					put(grammarAccess.getSimpleChartAccess().getClassAssignment_19(), "rule__SimpleChart__ClassAssignment_19");
					put(grammarAccess.getColorAccess().getNameAssignment_1(), "rule__Color__NameAssignment_1");
					put(grammarAccess.getColorAccess().getRgbAssignment_2(), "rule__Color__RgbAssignment_2");
					put(grammarAccess.getLabelAccess().getIdAssignment_1(), "rule__Label__IdAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.ckr.ui.contentassist.antlr.internal.InternalTabletUIDSLParser typedParser = (org.ckr.ui.contentassist.antlr.internal.InternalTabletUIDSLParser) parser;
			typedParser.entryRuleTabletUI();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public TabletUIDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TabletUIDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
